// Static recipe bank the mock LLM draws from to simulate `callLLM` for
// recipe generation. Replace `callLLM` in lib/llm.js with a real API call
// and this file is no longer needed by the app.

export const MOCK_RECIPES = {
  Breakfast: [
    {
      title: "Shakshuka",
      description:
        "Eggs poached in a spiced tomato and pepper sauce, finished with crumbled feta.",
      cuisine: "Mediterranean",
      dietary_tags: ["Vegetarian"],
      time_minutes: 25,
      servings: 2,
      ingredients: [
        "2 tbsp olive oil",
        "1 onion, diced",
        "1 red bell pepper, diced",
        "2 cloves garlic, minced",
        "1 tsp ground cumin",
        "1 tsp smoked paprika",
        "1 can (400g) crushed tomatoes",
        "4 eggs",
        "60g feta, crumbled",
        "Fresh parsley, chopped",
      ],
      steps: [
        "Heat olive oil in a wide skillet over medium heat and soften the onion and pepper, about 6 minutes.",
        "Stir in garlic, cumin, and paprika and cook for 1 minute until fragrant.",
        "Pour in the crushed tomatoes, season, and simmer for 8 minutes until thickened.",
        "Make four wells in the sauce and crack an egg into each one.",
        "Cover and cook for 6-8 minutes until whites are set but yolks are still runny.",
        "Scatter feta and parsley over the top and serve straight from the pan.",
      ],
    },
    {
      title: "Classic French Toast",
      description:
        "Thick brioche slices soaked in a vanilla-cinnamon custard and pan-fried until golden.",
      cuisine: "French",
      dietary_tags: ["Vegetarian"],
      time_minutes: 15,
      servings: 2,
      ingredients: [
        "4 thick slices brioche",
        "2 eggs",
        "120ml whole milk",
        "1 tsp vanilla extract",
        "1/2 tsp ground cinnamon",
        "1 tbsp butter",
        "Maple syrup, to serve",
      ],
      steps: [
        "Whisk eggs, milk, vanilla, and cinnamon together in a shallow dish.",
        "Soak each brioche slice for 20 seconds per side.",
        "Melt butter in a skillet over medium heat and fry the slices 2-3 minutes per side until golden.",
        "Serve warm with maple syrup.",
      ],
    },
    {
      title: "Tamagoyaki with Steamed Rice",
      description:
        "Rolled Japanese omelette seasoned with soy and mirin, served over rice.",
      cuisine: "Japanese",
      dietary_tags: ["Gluten-Free"],
      time_minutes: 20,
      servings: 2,
      ingredients: [
        "4 eggs",
        "1 tbsp mirin",
        "1 tsp soy sauce",
        "1/2 tsp sugar",
        "Neutral oil, for the pan",
        "1 cup steamed rice",
        "1 sheet nori, sliced",
      ],
      steps: [
        "Whisk eggs with mirin, soy sauce, and sugar.",
        "Heat a lightly oiled non-stick pan over medium-low heat and pour in a thin layer of egg.",
        "As it sets, roll it to one side, oil the pan again, and pour in more egg, rolling it into the first layer. Repeat until egg is used up.",
        "Slice the roll and serve warm over steamed rice with nori.",
      ],
    },
    {
      title: "Avocado & Feta Toast",
      description:
        "Toasted sourdough topped with smashed avocado, feta, and chili flakes.",
      cuisine: "Mediterranean",
      dietary_tags: ["Vegetarian"],
      time_minutes: 10,
      servings: 1,
      ingredients: [
        "2 slices sourdough bread",
        "1 ripe avocado",
        "40g feta, crumbled",
        "1/2 lemon, juiced",
        "Pinch of chili flakes",
        "Flaky salt",
      ],
      steps: [
        "Toast the sourdough until golden.",
        "Mash the avocado with lemon juice and a pinch of salt.",
        "Spread over the toast and top with feta and chili flakes.",
      ],
    },
    {
      title: "Huevos Rancheros",
      description:
        "Fried eggs over crisp tortillas with a warm ranchero sauce and black beans.",
      cuisine: "Mexican",
      dietary_tags: ["Vegetarian"],
      time_minutes: 25,
      servings: 2,
      ingredients: [
        "4 corn tortillas",
        "1 tbsp vegetable oil",
        "1 cup ranchero (tomato-chili) sauce",
        "1 cup black beans, warmed",
        "4 eggs",
        "1/4 cup cotija cheese, crumbled",
        "Fresh cilantro",
      ],
      steps: [
        "Lightly fry the tortillas in oil until just crisp, then set on plates.",
        "Warm the ranchero sauce in a small pan.",
        "Fry the eggs sunny-side up in the same pan.",
        "Layer beans and sauce over the tortillas, top with eggs, cotija, and cilantro.",
      ],
    },
    {
      title: "Overnight Oats with Berries",
      description:
        "No-cook oats soaked in oat milk with chia seeds, topped with fresh berries.",
      cuisine: "American",
      dietary_tags: ["Vegan"],
      time_minutes: 10,
      servings: 1,
      ingredients: [
        "1/2 cup rolled oats",
        "3/4 cup oat milk",
        "1 tbsp chia seeds",
        "1 tsp maple syrup",
        "1/2 cup mixed berries",
        "1 tbsp almond butter",
      ],
      steps: [
        "Stir oats, oat milk, chia seeds, and maple syrup together in a jar.",
        "Cover and refrigerate overnight (or at least 4 hours).",
        "Top with berries and almond butter before serving.",
      ],
    },
    {
      title: "Ginger Scallion Congee",
      description:
        "Slow-simmered rice porridge finished with crispy shallots and scallions.",
      cuisine: "Chinese",
      dietary_tags: ["Vegan"],
      time_minutes: 45,
      servings: 2,
      ingredients: [
        "3/4 cup jasmine rice",
        "6 cups vegetable stock",
        "1 knob ginger, sliced",
        "2 scallions, sliced",
        "2 tbsp crispy fried shallots",
        "1 tsp sesame oil",
        "Soy sauce, to taste",
      ],
      steps: [
        "Combine rice, stock, and ginger in a pot and bring to a boil.",
        "Reduce heat and simmer uncovered, stirring occasionally, for 35-40 minutes until thick and creamy.",
        "Discard the ginger slices and season with soy sauce.",
        "Ladle into bowls and top with scallions, crispy shallots, and a drizzle of sesame oil.",
      ],
    },
    {
      title: "Full English Breakfast",
      description:
        "Eggs, grilled tomatoes, mushrooms, sausages, and beans on one plate.",
      cuisine: "British",
      dietary_tags: [],
      time_minutes: 35,
      servings: 2,
      ingredients: [
        "4 sausages",
        "4 rashers bacon",
        "2 eggs",
        "1 can baked beans",
        "1 cup mushrooms, sliced",
        "2 tomatoes, halved",
        "2 slices toast",
      ],
      steps: [
        "Grill sausages and bacon until cooked through, about 15 minutes.",
        "Fry mushrooms and tomatoes in the rendered fat until soft.",
        "Warm the beans in a small pan.",
        "Fry the eggs to your liking and plate everything together with toast.",
      ],
    },
    {
      title: "Masala Dosa",
      description:
        "Crisp fermented rice-lentil crepe filled with spiced potato, served with coconut chutney.",
      cuisine: "Indian",
      dietary_tags: ["Vegan"],
      time_minutes: 50,
      servings: 2,
      ingredients: [
        "2 cups dosa batter (rice & urad dal)",
        "2 potatoes, boiled and cubed",
        "1 onion, sliced",
        "1 tsp mustard seeds",
        "1 sprig curry leaves",
        "1/2 tsp turmeric",
        "Coconut chutney, to serve",
      ],
      steps: [
        "Sauté mustard seeds and curry leaves in oil until they pop.",
        "Add onion and cook until soft, then stir in turmeric and potatoes, mashing slightly. Season and set aside.",
        "Spread a ladle of batter thinly on a hot griddle into a large crepe.",
        "Drizzle with oil and cook until crisp and golden underneath.",
        "Spoon the potato filling onto the dosa, fold, and serve with coconut chutney.",
      ],
    },
    {
      title: "Greek Yogurt Parfait",
      description:
        "Layered yogurt, honey, and granola with fresh fruit.",
      cuisine: "Mediterranean",
      dietary_tags: ["Vegetarian", "Gluten-Free"],
      time_minutes: 8,
      servings: 1,
      ingredients: [
        "1 cup Greek yogurt",
        "2 tbsp honey",
        "1/3 cup granola",
        "1/2 cup sliced strawberries",
        "1 tbsp chopped walnuts",
      ],
      steps: [
        "Spoon a third of the yogurt into a glass.",
        "Layer with honey, granola, and strawberries, repeating twice more.",
        "Top with walnuts and a final drizzle of honey.",
      ],
    },
  ],
  Lunch: [
    {
      title: "Banh Mi Sandwich",
      description:
        "Crusty baguette with pickled vegetables, pâté, and fresh herbs.",
      cuisine: "Vietnamese",
      dietary_tags: [],
      time_minutes: 30,
      servings: 2,
      ingredients: [
        "1 baguette, split",
        "150g pork pâté",
        "1 cup julienned carrot & daikon, quick-pickled",
        "1/2 cucumber, sliced",
        "2 tbsp mayonnaise",
        "1 chili, sliced",
        "Fresh cilantro",
      ],
      steps: [
        "Quick-pickle the carrot and daikon in vinegar, sugar, and salt for 20 minutes.",
        "Spread mayonnaise and pâté along the baguette.",
        "Layer in pickled vegetables, cucumber, chili, and cilantro.",
        "Press together and slice to serve.",
      ],
    },
    {
      title: "Caprese Panini",
      description:
        "Grilled ciabatta with mozzarella, tomato, basil, and balsamic glaze.",
      cuisine: "Italian",
      dietary_tags: ["Vegetarian"],
      time_minutes: 15,
      servings: 2,
      ingredients: [
        "4 slices ciabatta",
        "150g fresh mozzarella, sliced",
        "1 large tomato, sliced",
        "Fresh basil leaves",
        "2 tbsp balsamic glaze",
        "Olive oil, for grilling",
      ],
      steps: [
        "Layer mozzarella, tomato, and basil between ciabatta slices.",
        "Brush the outside with olive oil.",
        "Grill in a panini press or skillet until golden and the cheese melts, about 4 minutes per side.",
        "Drizzle with balsamic glaze before serving.",
      ],
    },
    {
      title: "Thai Larb Salad",
      description:
        "Minced chicken salad tossed with lime, fish sauce, herbs, and toasted rice powder.",
      cuisine: "Thai",
      dietary_tags: ["Gluten-Free"],
      time_minutes: 25,
      servings: 2,
      ingredients: [
        "400g ground chicken",
        "3 tbsp lime juice",
        "2 tbsp fish sauce",
        "1 tsp sugar",
        "1 tbsp toasted rice powder",
        "1/4 cup mint leaves",
        "1/4 cup cilantro",
        "2 shallots, thinly sliced",
        "Lettuce leaves, to serve",
      ],
      steps: [
        "Cook ground chicken in a dry skillet over medium heat until no longer pink, breaking it up as it cooks.",
        "Remove from heat and stir in lime juice, fish sauce, and sugar.",
        "Fold in rice powder, shallots, mint, and cilantro.",
        "Serve spooned into lettuce leaves.",
      ],
    },
    {
      title: "Falafel Wrap with Tahini",
      description:
        "Crisp chickpea falafel wrapped in flatbread with salad and tahini sauce.",
      cuisine: "Mediterranean",
      dietary_tags: ["Vegan"],
      time_minutes: 30,
      servings: 2,
      ingredients: [
        "8 pre-made or homemade falafel",
        "2 flatbreads",
        "1/2 cup shredded lettuce",
        "1 tomato, diced",
        "1/4 red onion, sliced",
        "3 tbsp tahini",
        "1 tbsp lemon juice",
        "Water, to thin",
      ],
      steps: [
        "Warm the falafel through in a hot pan or oven.",
        "Whisk tahini, lemon juice, and enough water to make a pourable sauce.",
        "Warm the flatbreads and fill with falafel, lettuce, tomato, and onion.",
        "Drizzle generously with tahini sauce and roll up.",
      ],
    },
    {
      title: "Chicken Caesar Salad",
      description:
        "Grilled chicken over crisp romaine with parmesan, croutons, and Caesar dressing.",
      cuisine: "American",
      dietary_tags: [],
      time_minutes: 20,
      servings: 2,
      ingredients: [
        "2 chicken breasts",
        "1 head romaine lettuce, chopped",
        "1/2 cup croutons",
        "1/3 cup shaved parmesan",
        "1/3 cup Caesar dressing",
        "Salt and pepper",
      ],
      steps: [
        "Season chicken breasts and grill or pan-sear until cooked through, about 6-7 minutes per side.",
        "Let rest, then slice.",
        "Toss romaine with Caesar dressing and plate.",
        "Top with sliced chicken, croutons, and parmesan.",
      ],
    },
    {
      title: "Miso Ramen Bowl",
      description:
        "Rich miso broth ramen with soft egg, corn, and scallions.",
      cuisine: "Japanese",
      dietary_tags: [],
      time_minutes: 40,
      servings: 2,
      ingredients: [
        "2 portions ramen noodles",
        "4 cups chicken or vegetable stock",
        "3 tbsp miso paste",
        "1 tbsp soy sauce",
        "2 soft-boiled eggs, halved",
        "1/2 cup corn kernels",
        "2 scallions, sliced",
        "Chili oil, to taste",
      ],
      steps: [
        "Bring the stock to a simmer and whisk in miso paste and soy sauce until dissolved.",
        "Cook ramen noodles separately according to package instructions.",
        "Divide noodles between bowls and ladle the broth over.",
        "Top with soft-boiled egg, corn, scallions, and a drizzle of chili oil.",
      ],
    },
    {
      title: "Black Bean Quesadillas",
      description:
        "Melty cheese and black bean quesadillas with a squeeze of lime.",
      cuisine: "Mexican",
      dietary_tags: ["Vegetarian"],
      time_minutes: 20,
      servings: 2,
      ingredients: [
        "4 flour tortillas",
        "1 cup black beans, drained",
        "1 1/2 cups shredded cheddar or Monterey Jack",
        "1/2 cup corn kernels",
        "1/2 tsp cumin",
        "Lime wedges, to serve",
      ],
      steps: [
        "Mash the black beans lightly with cumin.",
        "Spread beans, corn, and cheese over half of each tortilla and fold over.",
        "Cook in a dry skillet over medium heat, 2-3 minutes per side, until golden and the cheese melts.",
        "Cut into wedges and serve with lime.",
      ],
    },
    {
      title: "Greek Chickpea Salad",
      description:
        "Chickpeas, cucumber, tomato, and feta tossed in a lemon-oregano dressing.",
      cuisine: "Mediterranean",
      dietary_tags: ["Vegan", "Gluten-Free"],
      time_minutes: 15,
      servings: 2,
      ingredients: [
        "2 cups cooked chickpeas",
        "1 cucumber, diced",
        "1 cup cherry tomatoes, halved",
        "1/3 cup kalamata olives",
        "3 tbsp olive oil",
        "1 lemon, juiced",
        "1 tsp dried oregano",
      ],
      steps: [
        "Combine chickpeas, cucumber, tomatoes, and olives in a bowl.",
        "Whisk olive oil, lemon juice, and oregano together.",
        "Toss the dressing through the salad and season to taste.",
      ],
    },
    {
      title: "Reuben Sandwich",
      description:
        "Grilled rye piled with pastrami, sauerkraut, Swiss, and Russian dressing.",
      cuisine: "American",
      dietary_tags: [],
      time_minutes: 20,
      servings: 1,
      ingredients: [
        "2 slices rye bread",
        "120g pastrami",
        "1/2 cup sauerkraut, drained",
        "2 slices Swiss cheese",
        "2 tbsp Russian dressing",
        "1 tbsp butter",
      ],
      steps: [
        "Spread Russian dressing on both slices of bread.",
        "Layer pastrami, sauerkraut, and Swiss cheese between the slices.",
        "Butter the outside and grill in a skillet until golden and the cheese melts, about 3 minutes per side.",
      ],
    },
    {
      title: "Pad Thai",
      description:
        "Stir-fried rice noodles with tamarind sauce, egg, tofu, and crushed peanuts.",
      cuisine: "Thai",
      dietary_tags: ["Gluten-Free"],
      time_minutes: 35,
      servings: 2,
      ingredients: [
        "200g flat rice noodles",
        "150g firm tofu, cubed",
        "2 eggs",
        "3 tbsp tamarind paste",
        "2 tbsp fish sauce",
        "1 tbsp palm sugar",
        "1 cup bean sprouts",
        "1/4 cup crushed peanuts",
        "1 lime, cut into wedges",
      ],
      steps: [
        "Soak rice noodles in warm water until pliable, then drain.",
        "Stir-fry tofu in a hot wok until golden, push to the side, then scramble the eggs.",
        "Add noodles and the tamarind, fish sauce, and palm sugar mixture. Toss to combine.",
        "Fold in bean sprouts and cook 1-2 minutes more.",
        "Top with peanuts and serve with lime wedges.",
      ],
    },
    {
      title: "French Onion Soup",
      description:
        "Deeply caramelized onions in beef broth, topped with a Gruyère-crusted toast.",
      cuisine: "French",
      dietary_tags: ["Vegetarian"],
      time_minutes: 55,
      servings: 2,
      ingredients: [
        "4 large onions, thinly sliced",
        "3 tbsp butter",
        "1L vegetable stock",
        "1/2 cup dry white wine",
        "2 slices baguette",
        "1 cup grated Gruyère",
        "1 tsp fresh thyme",
      ],
      steps: [
        "Melt butter in a pot and cook onions low and slow, stirring often, for 30-35 minutes until deeply caramelized.",
        "Deglaze with wine, then add stock and thyme and simmer 15 minutes.",
        "Ladle into oven-safe bowls, top with baguette and Gruyère.",
        "Broil until the cheese is bubbling and golden.",
      ],
    },
    {
      title: "Butter Chicken",
      description:
        "Tender chicken in a creamy spiced tomato sauce, served with basmati rice.",
      cuisine: "Indian",
      dietary_tags: ["Gluten-Free"],
      time_minutes: 45,
      servings: 2,
      ingredients: [
        "500g chicken thighs, cubed",
        "1/2 cup plain yogurt",
        "2 tsp garam masala",
        "3 tbsp butter",
        "1 onion, diced",
        "3 cloves garlic, minced",
        "1 can (400g) tomato purée",
        "1/2 cup cream",
        "2 cups cooked basmati rice",
      ],
      steps: [
        "Marinate chicken in yogurt and half the garam masala for at least 15 minutes.",
        "Sear the chicken in butter until browned, then set aside.",
        "In the same pot, soften onion and garlic, then stir in tomato purée and remaining garam masala. Simmer 10 minutes.",
        "Return chicken to the pot, stir in cream, and simmer until cooked through, about 12 minutes.",
        "Serve over basmati rice.",
      ],
    },
  ],
  Dinner: [
    {
      title: "Spaghetti Carbonara",
      description:
        "Silky egg and pecorino sauce clinging to spaghetti with crisp guanciale.",
      cuisine: "Italian",
      dietary_tags: [],
      time_minutes: 25,
      servings: 2,
      ingredients: [
        "200g spaghetti",
        "100g guanciale or pancetta, diced",
        "2 whole eggs",
        "2 egg yolks",
        "60g pecorino romano, grated",
        "Black pepper, to taste",
      ],
      steps: [
        "Cook spaghetti in salted boiling water until al dente, reserving a cup of pasta water.",
        "Render guanciale in a skillet until crisp.",
        "Whisk eggs, yolks, and pecorino together in a bowl.",
        "Off the heat, toss the hot pasta with the guanciale, then quickly stir in the egg mixture, loosening with pasta water until glossy.",
        "Finish with plenty of black pepper.",
      ],
    },
    {
      title: "Chicken Tikka Masala",
      description:
        "Charred marinated chicken in a creamy spiced tomato sauce.",
      cuisine: "Indian",
      dietary_tags: ["Gluten-Free"],
      time_minutes: 45,
      servings: 4,
      ingredients: [
        "600g chicken thighs, cubed",
        "1 cup plain yogurt",
        "2 tbsp tikka spice blend",
        "2 tbsp ghee",
        "1 onion, diced",
        "1 can (400g) crushed tomatoes",
        "1/2 cup cream",
        "Fresh cilantro, to serve",
      ],
      steps: [
        "Marinate chicken in yogurt and spice blend for at least 20 minutes.",
        "Sear the chicken under a hot broiler or in a hot pan until charred at the edges.",
        "Sauté onion in ghee until soft, add crushed tomatoes, and simmer 10 minutes.",
        "Stir in cream and the seared chicken, simmering until cooked through, about 10 minutes.",
        "Garnish with cilantro and serve.",
      ],
    },
    {
      title: "Beef Bourguignon",
      description:
        "Red wine-braised beef with mushrooms, pearl onions, and lardons.",
      cuisine: "French",
      dietary_tags: [],
      time_minutes: 150,
      servings: 4,
      ingredients: [
        "1kg beef chuck, cubed",
        "150g bacon lardons",
        "2 cups red wine",
        "2 cups beef stock",
        "2 tbsp tomato paste",
        "12 pearl onions",
        "250g mushrooms, halved",
        "2 cloves garlic, minced",
        "2 sprigs thyme",
      ],
      steps: [
        "Brown the beef in batches in a heavy pot, then set aside.",
        "Render the lardons in the same pot, then soften garlic.",
        "Stir in tomato paste, then deglaze with wine and add stock, thyme, and browned beef.",
        "Cover and braise on low heat (or in a 150°C oven) for about 2 hours.",
        "Add pearl onions and mushrooms and cook a further 30 minutes until the beef is fork-tender.",
      ],
    },
    {
      title: "Pan-Seared Salmon with Lemon Butter",
      description:
        "Crisp-skinned salmon fillets in a bright lemon-caper butter sauce.",
      cuisine: "American",
      dietary_tags: ["Gluten-Free"],
      time_minutes: 25,
      servings: 2,
      ingredients: [
        "2 salmon fillets",
        "2 tbsp olive oil",
        "3 tbsp butter",
        "1 lemon, juiced",
        "1 tbsp capers",
        "2 cloves garlic, minced",
        "Fresh dill, chopped",
      ],
      steps: [
        "Pat the salmon dry and season well.",
        "Sear skin-side down in hot oil for 5 minutes, flip, and cook 3 more minutes. Remove and set aside.",
        "Melt butter in the same pan, add garlic and capers, then stir in lemon juice.",
        "Spoon the sauce over the salmon and top with dill.",
      ],
    },
    {
      title: "Vegetable Pad See Ew",
      description:
        "Wide rice noodles stir-fried in a sweet soy sauce with Chinese broccoli.",
      cuisine: "Thai",
      dietary_tags: ["Vegan"],
      time_minutes: 25,
      servings: 2,
      ingredients: [
        "250g wide rice noodles",
        "2 cups Chinese broccoli, chopped",
        "3 tbsp dark soy sauce",
        "2 tbsp soy sauce",
        "1 tbsp sugar",
        "3 cloves garlic, minced",
        "2 tbsp neutral oil",
      ],
      steps: [
        "Soak or prepare rice noodles according to package instructions.",
        "Heat oil in a wok and stir-fry garlic until fragrant.",
        "Add Chinese broccoli and cook until just tender.",
        "Add noodles, dark soy sauce, soy sauce, and sugar, tossing over high heat until noodles char slightly.",
      ],
    },
    {
      title: "Margherita Pizza from Scratch",
      description:
        "Homemade pizza dough topped with tomato, fresh mozzarella, and basil.",
      cuisine: "Italian",
      dietary_tags: ["Vegetarian"],
      time_minutes: 50,
      servings: 2,
      ingredients: [
        "1 ball pizza dough",
        "1/2 cup crushed tomatoes",
        "150g fresh mozzarella, torn",
        "Fresh basil leaves",
        "2 tbsp olive oil",
        "Flour, for dusting",
      ],
      steps: [
        "Preheat oven and pizza stone (if using) as hot as it will go.",
        "Stretch the dough into a round on a floured surface.",
        "Spread crushed tomatoes over the dough, leaving a border for the crust.",
        "Scatter mozzarella and drizzle with olive oil.",
        "Bake until the crust is blistered and golden, about 8-10 minutes.",
        "Top with fresh basil before serving.",
      ],
    },
    {
      title: "Korean Bibimbap",
      description:
        "Rice bowl topped with seasoned vegetables, a fried egg, and gochujang.",
      cuisine: "Korean",
      dietary_tags: ["Vegetarian"],
      time_minutes: 35,
      servings: 2,
      ingredients: [
        "2 cups cooked short-grain rice",
        "1 carrot, julienned",
        "1 zucchini, julienned",
        "1 cup spinach",
        "1 cup bean sprouts",
        "2 eggs",
        "2 tbsp gochujang",
        "1 tbsp sesame oil",
        "Sesame seeds",
      ],
      steps: [
        "Sauté carrot, zucchini, spinach, and bean sprouts separately, each with a little sesame oil and salt.",
        "Fry the eggs sunny-side up.",
        "Divide rice between bowls and arrange the vegetables around the edge.",
        "Top with a fried egg, a spoonful of gochujang, and a scattering of sesame seeds.",
      ],
    },
    {
      title: "Moroccan Chickpea Tagine",
      description:
        "Slow-simmered chickpeas, apricots, and warming spices over couscous.",
      cuisine: "Moroccan",
      dietary_tags: ["Vegan"],
      time_minutes: 50,
      servings: 4,
      ingredients: [
        "2 cans (400g each) chickpeas, drained",
        "1 onion, diced",
        "2 cloves garlic, minced",
        "1 tsp ground cumin",
        "1 tsp ground cinnamon",
        "1 tsp paprika",
        "1 can (400g) crushed tomatoes",
        "1/2 cup dried apricots, chopped",
        "2 cups cooked couscous",
      ],
      steps: [
        "Soften onion and garlic in a pot, then stir in the spices and cook for 1 minute.",
        "Add crushed tomatoes, chickpeas, and apricots, then simmer uncovered for 30-35 minutes until thickened.",
        "Season to taste and serve over couscous.",
      ],
    },
    {
      title: "Fish Tacos with Lime Slaw",
      description:
        "Blackened white fish in warm tortillas with a crunchy lime-cabbage slaw.",
      cuisine: "Mexican",
      dietary_tags: ["Gluten-Free"],
      time_minutes: 30,
      servings: 2,
      ingredients: [
        "400g white fish fillets",
        "1 tbsp Cajun or blackening spice",
        "8 small corn tortillas",
        "2 cups shredded cabbage",
        "2 tbsp mayonnaise",
        "1 lime, juiced",
        "1 avocado, sliced",
        "Fresh cilantro",
      ],
      steps: [
        "Coat the fish in blackening spice and pan-sear 3-4 minutes per side until flaky.",
        "Toss cabbage with mayonnaise and half the lime juice to make the slaw.",
        "Warm the tortillas and flake the fish into them.",
        "Top with slaw, avocado, cilantro, and a squeeze of the remaining lime.",
      ],
    },
    {
      title: "Mushroom Risotto",
      description:
        "Creamy arborio rice slow-stirred with mushrooms and parmesan.",
      cuisine: "Italian",
      dietary_tags: ["Vegetarian"],
      time_minutes: 40,
      servings: 2,
      ingredients: [
        "1 cup arborio rice",
        "300g mixed mushrooms, sliced",
        "4 cups warm vegetable stock",
        "1/2 cup dry white wine",
        "1 onion, finely diced",
        "1/2 cup parmesan, grated",
        "2 tbsp butter",
      ],
      steps: [
        "Sauté mushrooms in butter until golden, then set aside.",
        "In the same pot, soften onion, add rice, and toast for 1-2 minutes.",
        "Deglaze with wine, then add warm stock a ladle at a time, stirring until each addition is absorbed.",
        "Once the rice is creamy and just tender, stir in the mushrooms and parmesan.",
      ],
    },
    {
      title: "Roast Chicken with Root Vegetables",
      description:
        "Herb-rubbed whole chicken roasted over carrots, potatoes, and onions.",
      cuisine: "American",
      dietary_tags: ["Gluten-Free"],
      time_minutes: 75,
      servings: 4,
      ingredients: [
        "1 whole chicken (about 1.6kg)",
        "4 carrots, chopped",
        "4 potatoes, quartered",
        "2 onions, quartered",
        "3 tbsp olive oil",
        "1 tbsp fresh thyme",
        "1 lemon, halved",
      ],
      steps: [
        "Preheat oven to 200°C (400°F).",
        "Toss vegetables with half the oil and spread in a roasting pan.",
        "Rub the chicken with remaining oil and thyme, season generously, and stuff the cavity with lemon.",
        "Place the chicken on top of the vegetables and roast for about 60-70 minutes until the juices run clear.",
        "Rest for 10 minutes before carving.",
      ],
    },
    {
      title: "Eggplant Parmesan",
      description:
        "Layers of breaded eggplant, marinara, and melted mozzarella, baked until bubbling.",
      cuisine: "Italian",
      dietary_tags: ["Vegetarian"],
      time_minutes: 55,
      servings: 4,
      ingredients: [
        "2 large eggplants, sliced",
        "1 cup breadcrumbs",
        "1/2 cup grated parmesan",
        "2 eggs, beaten",
        "3 cups marinara sauce",
        "2 cups shredded mozzarella",
        "Fresh basil",
      ],
      steps: [
        "Dip eggplant slices in egg, then coat in breadcrumbs mixed with parmesan.",
        "Fry or bake the slices until golden on both sides.",
        "Layer eggplant, marinara, and mozzarella in a baking dish, repeating to fill it.",
        "Bake at 190°C (375°F) for 25-30 minutes until bubbling and golden.",
        "Rest 5 minutes, then top with fresh basil before serving.",
      ],
    },
  ],
};
