// Recipe bank the mock LLM draws from. Flat list so coverage is auditable:
// every cuisine in CUISINE_OPTIONS has real dishes for Breakfast, Lunch and
// Dinner. Dishes are the ones actually eaten for that meal in that cuisine —
// an Italian breakfast is a cornetto, not a plate of pasta.
//
// Dietary tags are literal: "Vegan" means no animal products anywhere in the
// ingredient list, and "Gluten-Free" excludes wheat, regular soy sauce and
// wheat noodles. Replace `callLLM` in lib/llm.js with a real API call and this
// file is no longer used.

export const MOCK_RECIPES = [
  // ---------------------------------------------------------------- Italian
  {
    slot: "Breakfast",
    title: "Cornetto e Cappuccino",
    description:
      "The standard Italian breakfast: a soft, sweet pastry with a milky coffee.",
    cuisine: "Italian",
    dietary_tags: ["Vegetarian"],
    time_minutes: 10,
    servings: 2,
    ingredients: [
      "2 cornetti (or good croissants)",
      "2 shots espresso",
      "200ml whole milk",
      "1 tsp apricot jam",
    ],
    steps: [
      "Warm the cornetti in a 160°C oven for 4 minutes.",
      "Pull two shots of espresso into large cups.",
      "Steam the milk until glossy with a fine foam and pour over the espresso.",
      "Serve immediately, with jam alongside if the cornetti are plain.",
    ],
  },
  {
    slot: "Breakfast",
    title: "Uova in Purgatorio",
    description:
      "Neapolitan eggs poached in a garlicky tomato sauce, eaten with bread.",
    cuisine: "Italian",
    dietary_tags: ["Vegetarian"],
    time_minutes: 20,
    servings: 2,
    ingredients: [
      "3 tbsp olive oil",
      "2 cloves garlic, sliced",
      "1 can (400g) peeled tomatoes, crushed by hand",
      "1 pinch dried chili flakes",
      "4 eggs",
      "2 tbsp grated pecorino",
      "Fresh basil",
      "4 slices crusty bread",
    ],
    steps: [
      "Warm the olive oil with the garlic and chili until the garlic turns pale gold.",
      "Add the tomatoes, season, and simmer for 10 minutes until slightly thickened.",
      "Crack the eggs into the sauce, cover, and cook 5-6 minutes until the whites set.",
      "Scatter with pecorino and basil and serve with bread for dipping.",
    ],
  },
  {
    slot: "Lunch",
    title: "Panzanella",
    description:
      "Tuscan bread salad that uses up stale bread with ripe tomatoes and basil.",
    cuisine: "Italian",
    dietary_tags: ["Vegan"],
    time_minutes: 20,
    servings: 2,
    ingredients: [
      "250g stale country bread, torn",
      "500g very ripe tomatoes, cut into chunks",
      "1/2 red onion, thinly sliced",
      "1 cucumber, chopped",
      "4 tbsp olive oil",
      "2 tbsp red wine vinegar",
      "Fresh basil leaves",
    ],
    steps: [
      "Salt the tomatoes in a bowl and leave 10 minutes to draw out their juice.",
      "Soak the onion in cold water for 10 minutes, then drain, to soften its bite.",
      "Toss the bread with the tomatoes and their juice so it softens but keeps some chew.",
      "Add cucumber, onion, oil and vinegar, toss, and rest 10 minutes before serving with basil.",
    ],
  },
  {
    slot: "Lunch",
    title: "Pasta e Fagioli",
    description:
      "Thick, humble soup of borlotti beans and short pasta from central Italy.",
    cuisine: "Italian",
    dietary_tags: ["Vegan"],
    time_minutes: 40,
    servings: 4,
    ingredients: [
      "3 tbsp olive oil",
      "1 onion, finely diced",
      "1 carrot, finely diced",
      "1 stick celery, finely diced",
      "2 cloves garlic, minced",
      "2 tbsp tomato paste",
      "2 cans (400g each) borlotti beans, drained",
      "1L vegetable stock",
      "200g ditalini or other small pasta",
      "1 sprig rosemary",
    ],
    steps: [
      "Soften the onion, carrot and celery in the oil over low heat for 10 minutes.",
      "Stir in the garlic and tomato paste and cook 2 minutes.",
      "Add the beans, stock and rosemary, then blend a third of the soup to thicken it.",
      "Return to a simmer, add the pasta, and cook until al dente. Loosen with water if needed.",
    ],
  },
  {
    slot: "Dinner",
    title: "Spaghetti alla Carbonara",
    description:
      "Roman pasta bound in egg and pecorino, with crisp guanciale. No cream.",
    cuisine: "Italian",
    dietary_tags: [],
    time_minutes: 25,
    servings: 2,
    ingredients: [
      "200g spaghetti",
      "100g guanciale, cut into strips",
      "2 whole eggs",
      "2 egg yolks",
      "60g pecorino romano, finely grated",
      "Black pepper, coarsely ground",
    ],
    steps: [
      "Render the guanciale in a cold, dry pan over medium heat until crisp; keep the fat.",
      "Cook the spaghetti in well-salted water until al dente, reserving a cup of the water.",
      "Beat the eggs, yolks, pecorino and plenty of pepper together in a bowl.",
      "Off the heat, toss the drained pasta with the guanciale and fat, then stir in the egg mixture, loosening with pasta water until glossy.",
      "Serve at once with more pecorino and pepper.",
    ],
  },
  {
    slot: "Dinner",
    title: "Melanzane alla Parmigiana",
    description:
      "Layered baked aubergine with tomato, basil and mozzarella from the south.",
    cuisine: "Italian",
    dietary_tags: ["Vegetarian"],
    time_minutes: 75,
    servings: 4,
    ingredients: [
      "2 large aubergines, sliced lengthways",
      "Olive oil, for frying",
      "700g passata",
      "2 cloves garlic, sliced",
      "250g mozzarella, torn and drained",
      "60g grated parmesan",
      "Fresh basil",
    ],
    steps: [
      "Salt the aubergine slices for 30 minutes, pat dry, then fry in oil until golden. Drain on paper.",
      "Simmer the passata with the garlic and a little oil for 15 minutes; season.",
      "Layer sauce, aubergine, mozzarella, basil and parmesan in a dish, repeating to fill.",
      "Bake at 180°C for 35-40 minutes until bubbling, then rest 15 minutes before cutting.",
    ],
  },
  {
    slot: "Dinner",
    title: "Risotto ai Funghi",
    description: "Creamy Northern Italian rice slowly stirred with mushrooms.",
    cuisine: "Italian",
    dietary_tags: ["Vegetarian"],
    time_minutes: 40,
    servings: 2,
    ingredients: [
      "180g carnaroli rice",
      "300g mixed mushrooms, sliced",
      "1L warm vegetable stock",
      "100ml dry white wine",
      "1 shallot, finely diced",
      "50g parmesan, grated",
      "40g cold butter",
    ],
    steps: [
      "Fry the mushrooms in butter over high heat until browned; set aside and season.",
      "Soften the shallot, add the rice, and toast for 2 minutes until the grains look translucent at the edges.",
      "Add the wine and let it evaporate, then add stock a ladleful at a time, stirring, for about 18 minutes.",
      "Off the heat, beat in the cold butter, parmesan and mushrooms and rest 2 minutes before serving.",
    ],
  },

  // ----------------------------------------------------------------- French
  {
    slot: "Breakfast",
    title: "Pain Perdu",
    description:
      "The original of French toast: stale brioche soaked in vanilla custard and fried.",
    cuisine: "French",
    dietary_tags: ["Vegetarian"],
    time_minutes: 15,
    servings: 2,
    ingredients: [
      "4 thick slices stale brioche",
      "2 eggs",
      "150ml whole milk",
      "1 tsp vanilla extract",
      "1 tbsp caster sugar",
      "30g butter",
      "Icing sugar, to finish",
    ],
    steps: [
      "Whisk the eggs, milk, vanilla and sugar in a shallow dish.",
      "Soak each slice for 30 seconds per side so the custard reaches the middle.",
      "Fry in foaming butter over medium heat, 2-3 minutes per side, until deep gold.",
      "Dust with icing sugar and serve straight away.",
    ],
  },
  {
    slot: "Breakfast",
    title: "Omelette aux Fines Herbes",
    description:
      "A pale, softly set French omelette rolled around fresh herbs.",
    cuisine: "French",
    dietary_tags: ["Vegetarian", "Gluten-Free"],
    time_minutes: 10,
    servings: 1,
    ingredients: [
      "3 eggs",
      "1 tbsp butter",
      "1 tbsp chopped chives",
      "1 tbsp chopped parsley",
      "1 tsp chopped tarragon",
      "Salt and white pepper",
    ],
    steps: [
      "Beat the eggs just until combined and season; do not whisk to a foam.",
      "Melt the butter in a non-stick pan over medium-low heat without letting it colour.",
      "Add the eggs and stir with a fork, shaking the pan, until softly scrambled but still wet.",
      "Scatter the herbs, then tilt the pan and roll the omelette onto a plate, seam down.",
    ],
  },
  {
    slot: "Lunch",
    title: "Croque Monsieur",
    description:
      "Grilled ham and cheese sandwich blanketed in béchamel and browned under a grill.",
    cuisine: "French",
    dietary_tags: [],
    time_minutes: 25,
    servings: 2,
    ingredients: [
      "4 slices white sandwich bread",
      "4 slices good ham",
      "120g Gruyère, grated",
      "25g butter",
      "25g plain flour",
      "300ml milk",
      "1 pinch grated nutmeg",
      "1 tsp Dijon mustard",
    ],
    steps: [
      "Melt the butter, stir in the flour and cook 1 minute, then whisk in the milk to a thick béchamel.",
      "Season with nutmeg, mustard, salt and pepper, then stir in a third of the Gruyère.",
      "Build sandwiches with ham and a little béchamel, then spread more béchamel over the tops.",
      "Cover with the rest of the Gruyère and grill until bubbling and browned, about 5 minutes.",
    ],
  },
  {
    slot: "Lunch",
    title: "Soupe à l'Oignon Gratinée",
    description:
      "Onions cooked down for the best part of an hour, under a raft of toasted cheese.",
    cuisine: "French",
    dietary_tags: [],
    time_minutes: 70,
    servings: 2,
    ingredients: [
      "5 large onions, thinly sliced",
      "40g butter",
      "1 tbsp olive oil",
      "1 tsp sugar",
      "150ml dry white wine",
      "1L beef stock",
      "2 sprigs thyme",
      "4 slices baguette",
      "100g Gruyère, grated",
    ],
    steps: [
      "Cook the onions in butter and oil over low heat with the sugar and a pinch of salt for 45 minutes, stirring often, until deep brown.",
      "Add the wine and scrape the base of the pan clean, letting it reduce by half.",
      "Pour in the stock, add the thyme, and simmer 20 minutes; season.",
      "Ladle into oven-safe bowls, float the baguette on top, cover with Gruyère and grill until blistered.",
    ],
  },
  {
    slot: "Lunch",
    title: "Salade Niçoise",
    description:
      "Composed salad from Nice with tuna, egg, olives and green beans.",
    cuisine: "French",
    dietary_tags: ["Gluten-Free", "Pescatarian"],
    time_minutes: 30,
    servings: 2,
    ingredients: [
      "200g green beans, trimmed",
      "3 eggs",
      "300g new potatoes",
      "160g tinned tuna in oil, drained",
      "12 Niçoise olives",
      "200g cherry tomatoes, halved",
      "4 tbsp olive oil",
      "1 tbsp red wine vinegar",
      "1 tsp Dijon mustard",
    ],
    steps: [
      "Boil the potatoes until tender, then the beans for 3 minutes; refresh both in cold water.",
      "Boil the eggs for 8 minutes, cool, peel and quarter.",
      "Whisk the oil, vinegar and mustard into a dressing and season.",
      "Arrange everything in groups on a platter rather than tossing, and spoon the dressing over.",
    ],
  },
  {
    slot: "Dinner",
    title: "Boeuf Bourguignon",
    description:
      "Burgundian beef braised slowly in red wine with mushrooms and lardons.",
    cuisine: "French",
    dietary_tags: [],
    time_minutes: 180,
    servings: 4,
    ingredients: [
      "1kg beef chuck, in large cubes",
      "150g bacon lardons",
      "750ml red Burgundy",
      "500ml beef stock",
      "2 tbsp tomato paste",
      "250g button mushrooms",
      "12 pearl onions, peeled",
      "2 carrots, in chunks",
      "1 bouquet garni",
    ],
    steps: [
      "Pat the beef dry and brown it hard in batches; do not crowd the pan. Set aside.",
      "Render the lardons, then soften the carrots and stir in the tomato paste.",
      "Return the beef, add the wine, stock and bouquet garni, and bring to a bare simmer.",
      "Cover and cook at 150°C for 2 hours, adding the onions and mushrooms for the last 30 minutes.",
      "Skim the fat, check the seasoning, and serve with potatoes or bread.",
    ],
  },
  {
    slot: "Dinner",
    title: "Coq au Vin",
    description: "Chicken braised in red wine with bacon, onions and mushrooms.",
    cuisine: "French",
    dietary_tags: [],
    time_minutes: 90,
    servings: 4,
    ingredients: [
      "8 bone-in chicken thighs",
      "120g bacon lardons",
      "500ml red wine",
      "300ml chicken stock",
      "250g chestnut mushrooms, halved",
      "10 shallots, peeled",
      "2 cloves garlic, crushed",
      "2 tbsp plain flour",
      "2 sprigs thyme",
    ],
    steps: [
      "Brown the chicken skin-side down until deeply coloured, then set aside.",
      "Render the lardons with the shallots and mushrooms until golden.",
      "Sprinkle over the flour, cook 1 minute, then add the wine, stock, garlic and thyme.",
      "Return the chicken, cover, and simmer gently for 45 minutes until tender and the sauce coats a spoon.",
    ],
  },

  // ---------------------------------------------------------------- Spanish
  {
    slot: "Breakfast",
    title: "Pan con Tomate",
    description:
      "Toasted bread rubbed with ripe tomato and garlic — the Catalan breakfast.",
    cuisine: "Spanish",
    dietary_tags: ["Vegan"],
    time_minutes: 10,
    servings: 2,
    ingredients: [
      "4 slices rustic bread",
      "2 very ripe tomatoes, halved",
      "1 clove garlic, halved",
      "3 tbsp extra virgin olive oil",
      "Flaky salt",
    ],
    steps: [
      "Toast the bread until crisp at the edges but still soft inside.",
      "Rub the cut garlic lightly over each slice while still warm.",
      "Rub the cut face of the tomato firmly into the bread so the pulp soaks in; discard the skin.",
      "Drizzle generously with olive oil and finish with flaky salt.",
    ],
  },
  {
    slot: "Breakfast",
    title: "Tortilla Española",
    description:
      "Thick potato and onion omelette, eaten at any hour and good warm or cold.",
    cuisine: "Spanish",
    dietary_tags: ["Vegetarian", "Gluten-Free"],
    time_minutes: 45,
    servings: 4,
    ingredients: [
      "600g waxy potatoes, thinly sliced",
      "1 large onion, thinly sliced",
      "250ml olive oil, for confiting",
      "6 eggs",
      "Salt",
    ],
    steps: [
      "Cook the potatoes and onion gently in the oil over low heat for 20 minutes until soft but not coloured, then drain well.",
      "Beat the eggs with plenty of salt and fold in the warm potatoes; rest 10 minutes.",
      "Cook in 2 tbsp of the oil in a non-stick pan over medium-low heat for 6 minutes until set at the edges.",
      "Invert onto a plate, slide back in, and cook 4 minutes more; the centre should stay slightly soft.",
    ],
  },
  {
    slot: "Lunch",
    title: "Gazpacho Andaluz",
    description: "Chilled raw tomato soup from Andalusia, drunk as much as eaten.",
    cuisine: "Spanish",
    dietary_tags: ["Vegan"],
    time_minutes: 20,
    servings: 4,
    ingredients: [
      "1kg very ripe tomatoes, quartered",
      "1 cucumber, peeled and chopped",
      "1 green pepper, chopped",
      "1 clove garlic",
      "50g stale bread, soaked in water",
      "80ml extra virgin olive oil",
      "2 tbsp sherry vinegar",
    ],
    steps: [
      "Blend the tomatoes, cucumber, pepper, garlic and soaked bread until completely smooth.",
      "With the blender running, pour in the olive oil to emulsify the soup.",
      "Season with the sherry vinegar and plenty of salt, then pass through a sieve for a silky texture.",
      "Chill for at least 2 hours and check the seasoning again before serving very cold.",
    ],
  },
  {
    slot: "Lunch",
    title: "Bocadillo de Tortilla",
    description:
      "Crusty roll packed with a wedge of potato omelette — the standard Spanish lunch to go.",
    cuisine: "Spanish",
    dietary_tags: ["Vegetarian"],
    time_minutes: 15,
    servings: 2,
    ingredients: [
      "2 crusty white rolls",
      "4 thick wedges cooked tortilla española",
      "2 ripe tomatoes, halved",
      "2 tbsp olive oil",
      "Salt",
    ],
    steps: [
      "Split the rolls and rub the cut sides with tomato, then drizzle with olive oil and salt.",
      "Lay the tortilla wedges inside, filling the roll edge to edge.",
      "Press the sandwich closed firmly and wrap in paper for 5 minutes before eating.",
    ],
  },
  {
    slot: "Dinner",
    title: "Paella de Marisco",
    description:
      "Saffron rice cooked flat and wide with seafood, prized for its crisp base.",
    cuisine: "Spanish",
    dietary_tags: ["Gluten-Free", "Pescatarian"],
    time_minutes: 50,
    servings: 4,
    ingredients: [
      "320g bomba rice",
      "1L fish stock, hot",
      "1 pinch saffron threads",
      "300g raw prawns, shell on",
      "300g mussels, cleaned",
      "200g squid rings",
      "1 onion, finely diced",
      "2 tomatoes, grated",
      "1 tsp sweet paprika",
      "4 tbsp olive oil",
    ],
    steps: [
      "Sear the prawns and squid briefly in the oil in a wide pan, then remove.",
      "Soften the onion, add the grated tomato and paprika, and cook down to a thick sofrito.",
      "Stir in the rice for 1 minute, then add the saffron and hot stock. Spread the rice flat and do not stir again.",
      "Simmer 10 minutes, add the seafood and mussels on top, and cook 8 minutes more.",
      "Raise the heat for 60-90 seconds to form the socarrat, then rest off the heat for 5 minutes.",
    ],
  },
  {
    slot: "Dinner",
    title: "Pollo al Ajillo",
    description: "Chicken browned hard with a great deal of garlic and sherry.",
    cuisine: "Spanish",
    dietary_tags: ["Gluten-Free", "Dairy-Free"],
    time_minutes: 40,
    servings: 4,
    ingredients: [
      "1 chicken, jointed into 8 pieces",
      "1 whole head garlic, cloves separated and peeled",
      "120ml dry sherry",
      "100ml olive oil",
      "2 bay leaves",
      "Fresh parsley, chopped",
    ],
    steps: [
      "Season the chicken well and brown it in the oil until golden on all sides.",
      "Add the whole garlic cloves and bay and cook until the garlic is soft and sweet, about 5 minutes.",
      "Pour in the sherry, scrape the pan, and let it bubble down by half.",
      "Cover and cook 20 minutes until the chicken is cooked through, then finish with parsley.",
    ],
  },

  // ------------------------------------------------------------------ Greek
  {
    slot: "Breakfast",
    title: "Strapatsada",
    description: "Eggs scrambled slowly into summer tomatoes with feta.",
    cuisine: "Greek",
    dietary_tags: ["Vegetarian", "Gluten-Free"],
    time_minutes: 20,
    servings: 2,
    ingredients: [
      "4 ripe tomatoes, grated",
      "4 eggs, beaten",
      "3 tbsp olive oil",
      "80g feta, crumbled",
      "1 pinch dried oregano",
      "Black pepper",
    ],
    steps: [
      "Cook the grated tomato in the olive oil over medium heat for 10 minutes until the liquid has gone and it looks jammy.",
      "Lower the heat and pour in the eggs, stirring slowly so they stay soft.",
      "Take off the heat while still creamy and fold through most of the feta.",
      "Finish with the rest of the feta, oregano and pepper.",
    ],
  },
  {
    slot: "Breakfast",
    title: "Greek Yogurt with Honey and Walnuts",
    description:
      "Thick strained yogurt with thyme honey and toasted walnuts.",
    cuisine: "Greek",
    dietary_tags: ["Vegetarian", "Gluten-Free"],
    time_minutes: 5,
    servings: 2,
    ingredients: [
      "400g full-fat Greek yogurt",
      "3 tbsp thyme honey",
      "60g walnuts, roughly chopped",
      "1 pinch ground cinnamon",
    ],
    steps: [
      "Toast the walnuts in a dry pan until fragrant, then cool slightly.",
      "Spoon the yogurt into bowls and make a well in the centre of each.",
      "Pour the honey into the well, scatter the walnuts over, and dust with cinnamon.",
    ],
  },
  {
    slot: "Lunch",
    title: "Horiatiki Salata",
    description:
      "The real Greek village salad — no lettuce, and the feta arrives in a slab.",
    cuisine: "Greek",
    dietary_tags: ["Vegetarian", "Gluten-Free"],
    time_minutes: 15,
    servings: 2,
    ingredients: [
      "4 ripe tomatoes, in wedges",
      "1 cucumber, in thick half-moons",
      "1/2 red onion, sliced",
      "1 green pepper, sliced into rings",
      "16 kalamata olives",
      "200g block feta",
      "4 tbsp extra virgin olive oil",
      "1 tsp dried oregano",
    ],
    steps: [
      "Put the tomatoes, cucumber, onion, pepper and olives in a wide bowl and salt lightly.",
      "Lay the whole slab of feta on top rather than crumbling it.",
      "Pour the olive oil over the feta and sprinkle generously with oregano.",
      "Serve with bread to mop the juices; do not toss before serving.",
    ],
  },
  {
    slot: "Lunch",
    title: "Chicken Souvlaki Pita",
    description:
      "Skewered marinated chicken wrapped in warm pita with tzatziki.",
    cuisine: "Greek",
    dietary_tags: [],
    time_minutes: 35,
    servings: 2,
    ingredients: [
      "400g chicken thigh, cubed",
      "3 tbsp olive oil",
      "1 lemon, juiced",
      "2 cloves garlic, minced",
      "1 tsp dried oregano",
      "2 pita breads",
      "150g tzatziki",
      "1 tomato, sliced",
      "1/4 red onion, sliced",
    ],
    steps: [
      "Marinate the chicken in the oil, lemon, garlic and oregano for at least 20 minutes.",
      "Thread onto skewers and grill over high heat for 10-12 minutes, turning, until charred at the edges.",
      "Warm the pitas briefly on the grill so they stay pliable.",
      "Spread with tzatziki, add the chicken, tomato and onion, and roll tightly.",
    ],
  },
  {
    slot: "Dinner",
    title: "Moussaka",
    description:
      "Baked layers of aubergine and spiced lamb under a thick béchamel.",
    cuisine: "Greek",
    dietary_tags: [],
    time_minutes: 105,
    servings: 6,
    ingredients: [
      "3 aubergines, sliced",
      "500g minced lamb",
      "1 onion, diced",
      "2 cloves garlic, minced",
      "1 can (400g) chopped tomatoes",
      "1 tsp ground cinnamon",
      "60g butter",
      "60g plain flour",
      "600ml milk",
      "1 egg yolk",
      "60g kefalotyri or parmesan, grated",
    ],
    steps: [
      "Salt the aubergine slices for 30 minutes, pat dry, brush with oil and roast at 200°C for 20 minutes.",
      "Brown the lamb with the onion and garlic, then add the tomatoes and cinnamon and simmer 20 minutes until thick.",
      "Make a béchamel with the butter, flour and milk; off the heat beat in the yolk and half the cheese.",
      "Layer aubergine and lamb in a dish, pour the béchamel over, top with the rest of the cheese.",
      "Bake at 180°C for 45 minutes until golden, then rest 20 minutes before cutting.",
    ],
  },
  {
    slot: "Dinner",
    title: "Gemista",
    description:
      "Tomatoes and peppers stuffed with herbed rice and baked slowly in olive oil.",
    cuisine: "Greek",
    dietary_tags: ["Vegan"],
    time_minutes: 90,
    servings: 4,
    ingredients: [
      "4 large tomatoes",
      "4 bell peppers",
      "200g long-grain rice, uncooked",
      "1 onion, finely diced",
      "100ml olive oil",
      "1 bunch parsley, chopped",
      "2 tbsp chopped mint",
      "2 potatoes, cut into wedges",
    ],
    steps: [
      "Cut the tops off the vegetables and keep them as lids. Scoop out the tomato flesh and chop it.",
      "Soften the onion in half the oil, add the rice and tomato flesh, and cook 5 minutes; stir in the herbs.",
      "Fill the vegetables two-thirds full to leave room for the rice to swell, and replace the lids.",
      "Tuck the potato wedges around them, pour over the remaining oil and a cup of water, and bake at 180°C for 70 minutes.",
    ],
  },

  // --------------------------------------------------------- Middle Eastern
  {
    slot: "Breakfast",
    title: "Shakshuka",
    description:
      "Eggs poached in a cumin-scented pepper and tomato sauce, from the Maghreb.",
    cuisine: "Middle Eastern",
    dietary_tags: ["Vegetarian", "Gluten-Free"],
    time_minutes: 30,
    servings: 2,
    ingredients: [
      "3 tbsp olive oil",
      "1 onion, sliced",
      "2 red peppers, sliced",
      "3 cloves garlic, sliced",
      "1 tsp ground cumin",
      "1 tsp sweet paprika",
      "1 can (400g) chopped tomatoes",
      "4 eggs",
      "80g feta, crumbled",
      "Fresh coriander",
    ],
    steps: [
      "Cook the onion and peppers in the oil over medium heat for 12 minutes until soft and sweet.",
      "Add the garlic and spices and cook 1 minute until fragrant.",
      "Pour in the tomatoes, season, and simmer 10 minutes until thick enough to hold a trench.",
      "Make wells, crack in the eggs, cover and cook 6 minutes until the whites just set.",
      "Scatter with feta and coriander and serve from the pan with bread.",
    ],
  },
  {
    slot: "Breakfast",
    title: "Ful Medames",
    description:
      "Slow-cooked fava beans dressed with lemon, olive oil and cumin — an Egyptian staple.",
    cuisine: "Middle Eastern",
    dietary_tags: ["Vegan"],
    time_minutes: 20,
    servings: 2,
    ingredients: [
      "2 cans (400g each) fava beans, drained",
      "3 tbsp extra virgin olive oil",
      "1 lemon, juiced",
      "2 cloves garlic, crushed",
      "1 tsp ground cumin",
      "1 tomato, diced",
      "Fresh parsley, chopped",
      "Warm flatbread, to serve",
    ],
    steps: [
      "Warm the beans in a little water over low heat for 10 minutes, then mash about half of them.",
      "Stir in the garlic, cumin, lemon juice and most of the olive oil; season well.",
      "Top with tomato, parsley and the last of the oil.",
      "Serve hot with flatbread for scooping.",
    ],
  },
  {
    slot: "Lunch",
    title: "Falafel Wrap",
    description:
      "Crisp fried chickpea patties rolled into flatbread with salad and tahini.",
    cuisine: "Middle Eastern",
    dietary_tags: ["Vegan"],
    time_minutes: 40,
    servings: 2,
    ingredients: [
      "250g dried chickpeas, soaked overnight (not tinned)",
      "1 onion, quartered",
      "3 cloves garlic",
      "1 bunch parsley",
      "1 tsp ground cumin",
      "1 tsp baking powder",
      "Oil, for frying",
      "2 flatbreads",
      "3 tbsp tahini",
      "1 lemon, juiced",
    ],
    steps: [
      "Blitz the drained soaked chickpeas with the onion, garlic, parsley and cumin to a coarse, sandy paste. Do not use tinned chickpeas — they will fall apart.",
      "Stir in the baking powder, season, and chill 30 minutes. Shape into small patties.",
      "Fry at 170°C for 3-4 minutes until deep brown and crisp; drain.",
      "Loosen the tahini with lemon juice and cold water until pourable.",
      "Fill the flatbreads with salad and falafel and spoon the tahini over.",
    ],
  },
  {
    slot: "Lunch",
    title: "Fattoush",
    description:
      "Levantine bread salad, sharp with sumac and studded with crisp pita.",
    cuisine: "Middle Eastern",
    dietary_tags: ["Vegan"],
    time_minutes: 20,
    servings: 4,
    ingredients: [
      "2 pita breads, torn",
      "4 tbsp olive oil",
      "3 tomatoes, chopped",
      "1 cucumber, chopped",
      "4 radishes, sliced",
      "4 spring onions, sliced",
      "1 bunch parsley, chopped",
      "1 bunch mint, chopped",
      "2 tbsp sumac",
      "1 lemon, juiced",
      "1 tbsp pomegranate molasses",
    ],
    steps: [
      "Toss the torn pita with half the oil and bake at 190°C for 8 minutes until crisp.",
      "Combine the tomatoes, cucumber, radish, spring onion and herbs in a wide bowl.",
      "Whisk the remaining oil with the lemon, pomegranate molasses and most of the sumac.",
      "Add the pita only just before serving so it keeps its crunch, then dress and finish with sumac.",
    ],
  },
  {
    slot: "Dinner",
    title: "Chicken Shawarma",
    description:
      "Spiced marinated chicken roasted hard and shaved into flatbread with garlic sauce.",
    cuisine: "Middle Eastern",
    dietary_tags: [],
    time_minutes: 50,
    servings: 4,
    ingredients: [
      "800g chicken thighs, boneless",
      "3 tbsp olive oil",
      "2 tsp ground cumin",
      "2 tsp ground coriander",
      "1 tsp ground turmeric",
      "1 tsp smoked paprika",
      "1/2 tsp ground cinnamon",
      "1 lemon, juiced",
      "4 cloves garlic, crushed",
      "4 flatbreads",
      "150g garlic toum or yogurt sauce",
    ],
    steps: [
      "Mix the oil, spices, lemon and garlic and marinate the thighs for at least 30 minutes.",
      "Stack the thighs tightly in a small roasting tin so they cook as one block.",
      "Roast at 220°C for 35-40 minutes until the edges char and the centre is cooked.",
      "Rest 10 minutes, then shave into thin slices and pile into flatbreads with the garlic sauce.",
    ],
  },
  {
    slot: "Dinner",
    title: "Kofta Kebab",
    description:
      "Minced lamb skewers with onion, parsley and warm spice, grilled hard.",
    cuisine: "Middle Eastern",
    dietary_tags: ["Dairy-Free"],
    time_minutes: 35,
    servings: 4,
    ingredients: [
      "600g minced lamb (20% fat)",
      "1 onion, grated and squeezed dry",
      "1 bunch parsley, finely chopped",
      "1 tsp ground allspice",
      "1 tsp ground cumin",
      "1/2 tsp chili flakes",
      "Flatbread and salad, to serve",
    ],
    steps: [
      "Knead the lamb with the onion, parsley and spices for 3 minutes until it turns slightly sticky — this is what stops it falling off the skewer.",
      "Chill 20 minutes, then shape around flat metal skewers into long fingers.",
      "Grill over high heat for 8-10 minutes, turning once, until well charred outside and just cooked within.",
      "Rest briefly and serve with flatbread and salad.",
    ],
  },

  // --------------------------------------------------------------- Moroccan
  {
    slot: "Breakfast",
    title: "Msemen with Honey",
    description:
      "Layered square flatbreads, pan-fried until flaky and eaten with butter and honey.",
    cuisine: "Moroccan",
    dietary_tags: ["Vegetarian"],
    time_minutes: 45,
    servings: 4,
    ingredients: [
      "300g fine semolina",
      "200g plain flour",
      "1 tsp salt",
      "300ml warm water",
      "60g softened butter",
      "60ml vegetable oil",
      "Honey, to serve",
    ],
    steps: [
      "Knead the semolina, flour, salt and water into a soft, smooth dough, about 8 minutes.",
      "Rest 20 minutes, then divide into balls and flatten each very thin on an oiled surface.",
      "Smear with butter and oil, fold into a square envelope, and rest again briefly.",
      "Fry in a dry pan over medium heat for 2-3 minutes per side until golden and layered.",
      "Serve hot, torn open, with honey.",
    ],
  },
  {
    slot: "Breakfast",
    title: "Baghrir",
    description:
      "Semolina pancakes riddled with tiny holes that drink up honey butter.",
    cuisine: "Moroccan",
    dietary_tags: ["Vegetarian"],
    time_minutes: 40,
    servings: 4,
    ingredients: [
      "250g fine semolina",
      "50g plain flour",
      "1 tsp baking powder",
      "1 tsp dried yeast",
      "1/2 tsp salt",
      "600ml warm water",
      "Honey and butter, to serve",
    ],
    steps: [
      "Blend all the dry ingredients with the warm water into a thin, smooth batter.",
      "Rest 20 minutes until visibly frothy on the surface.",
      "Pour ladlefuls into a dry non-stick pan over medium heat and cook on one side only, until the holes open and the top sets dry.",
      "Stack without turning and serve with honey warmed into butter.",
    ],
  },
  {
    slot: "Lunch",
    title: "Harira",
    description:
      "Tomato, lentil and chickpea soup thickened with flour and sharpened with lemon.",
    cuisine: "Moroccan",
    dietary_tags: ["Vegan"],
    time_minutes: 60,
    servings: 6,
    ingredients: [
      "150g brown lentils",
      "1 can (400g) chickpeas, drained",
      "1 onion, finely diced",
      "3 stalks celery, diced",
      "1 can (400g) chopped tomatoes",
      "1 tsp ground turmeric",
      "1 tsp ground ginger",
      "1 tsp ground cinnamon",
      "1 bunch coriander, chopped",
      "2 tbsp plain flour",
      "1.5L vegetable stock",
      "1 lemon, cut into wedges",
    ],
    steps: [
      "Soften the onion and celery, then add the spices and cook 1 minute.",
      "Add the tomatoes, lentils, chickpeas and stock and simmer 40 minutes until the lentils are soft.",
      "Whisk the flour into a cup of cold water and stir it in; simmer 10 minutes more to thicken.",
      "Stir through the coriander and serve with lemon wedges to squeeze over.",
    ],
  },
  {
    slot: "Lunch",
    title: "Zaalouk with Flatbread",
    description: "Smoky cooked salad of aubergine and tomato, eaten with bread.",
    cuisine: "Moroccan",
    dietary_tags: ["Vegan"],
    time_minutes: 40,
    servings: 4,
    ingredients: [
      "2 aubergines, peeled and cubed",
      "4 tomatoes, grated",
      "4 cloves garlic, minced",
      "4 tbsp olive oil",
      "1 tsp sweet paprika",
      "1 tsp ground cumin",
      "1 bunch coriander, chopped",
      "1 lemon, juiced",
      "Flatbread, to serve",
    ],
    steps: [
      "Steam or boil the aubergine for 15 minutes until completely collapsed, then drain well.",
      "Cook the garlic in the oil, add the grated tomato and spices, and reduce for 10 minutes.",
      "Add the aubergine and mash it into the sauce, cooking until thick and no liquid remains.",
      "Finish with coriander and lemon, and serve warm or at room temperature with bread.",
    ],
  },
  {
    slot: "Dinner",
    title: "Chicken Tagine with Preserved Lemon",
    description:
      "Slow-cooked chicken with olives, ginger and salt-cured lemon.",
    cuisine: "Moroccan",
    dietary_tags: ["Gluten-Free", "Dairy-Free"],
    time_minutes: 75,
    servings: 4,
    ingredients: [
      "8 bone-in chicken thighs",
      "2 onions, sliced",
      "3 cloves garlic, minced",
      "1 tsp ground ginger",
      "1 tsp ground turmeric",
      "1 pinch saffron",
      "1 preserved lemon, rind only, sliced",
      "120g green olives",
      "1 bunch coriander, chopped",
      "300ml chicken stock",
    ],
    steps: [
      "Brown the chicken in oil, then set aside.",
      "Soften the onions and garlic, stir in the ginger, turmeric and saffron.",
      "Return the chicken with the stock, cover, and simmer gently for 45 minutes.",
      "Add the preserved lemon and olives for the last 10 minutes, then finish with coriander.",
    ],
  },
  {
    slot: "Dinner",
    title: "Chickpea and Apricot Tagine",
    description:
      "Sweet-spiced chickpea stew with dried apricots, served over couscous.",
    cuisine: "Moroccan",
    dietary_tags: ["Vegan"],
    time_minutes: 50,
    servings: 4,
    ingredients: [
      "2 cans (400g each) chickpeas, drained",
      "1 onion, diced",
      "3 cloves garlic, minced",
      "1 tsp ground cumin",
      "1 tsp ground cinnamon",
      "1 tsp sweet paprika",
      "1 can (400g) chopped tomatoes",
      "100g dried apricots, halved",
      "300ml vegetable stock",
      "300g couscous",
    ],
    steps: [
      "Soften the onion and garlic, then toast the spices in the pan for 1 minute.",
      "Add the tomatoes, chickpeas, apricots and stock and simmer uncovered for 30 minutes until thick.",
      "Pour boiling stock over the couscous, cover, and steam 5 minutes, then fork through.",
      "Check the seasoning and serve the tagine over the couscous.",
    ],
  },

  // ----------------------------------------------------------------- Indian
  {
    slot: "Breakfast",
    title: "Masala Dosa",
    description:
      "Crisp fermented rice and lentil crepe folded around spiced potato.",
    cuisine: "Indian",
    dietary_tags: ["Vegan", "Gluten-Free"],
    time_minutes: 50,
    servings: 2,
    ingredients: [
      "400ml dosa batter (fermented rice and urad dal)",
      "3 potatoes, boiled and roughly crushed",
      "1 onion, sliced",
      "1 tsp black mustard seeds",
      "1 sprig curry leaves",
      "1/2 tsp ground turmeric",
      "2 green chillies, slit",
      "3 tbsp oil",
      "Coconut chutney, to serve",
    ],
    steps: [
      "Pop the mustard seeds in hot oil, add the curry leaves and chillies, then the onion, and cook until soft.",
      "Stir in the turmeric and potatoes, season, and cook 3 minutes. Set aside.",
      "Spread a ladle of batter thinly on a hot griddle in a spiral and drizzle oil round the edge.",
      "Cook without turning until the underside is lacy and deep gold and the dosa lifts freely.",
      "Spoon the potato along the centre, fold over, and serve with coconut chutney.",
    ],
  },
  {
    slot: "Breakfast",
    title: "Poha",
    description:
      "Flattened rice steamed with turmeric, peanuts and lime — a Maharashtrian morning staple.",
    cuisine: "Indian",
    dietary_tags: ["Vegan", "Gluten-Free"],
    time_minutes: 20,
    servings: 2,
    ingredients: [
      "200g thick poha (flattened rice)",
      "1 onion, finely diced",
      "1 potato, small diced",
      "50g raw peanuts",
      "1 tsp black mustard seeds",
      "1 sprig curry leaves",
      "1/2 tsp ground turmeric",
      "2 tbsp oil",
      "1 lime",
      "Fresh coriander",
    ],
    steps: [
      "Rinse the poha briefly in a sieve until just softened, then leave to drain — never soak it.",
      "Fry the peanuts in the oil until golden and set aside; pop the mustard seeds and curry leaves in the same oil.",
      "Add the potato and cook until tender, then the onion until translucent, then the turmeric.",
      "Fold in the poha gently with salt and a splash of water, cover and steam 3 minutes.",
      "Finish with the peanuts, plenty of lime and coriander.",
    ],
  },
  {
    slot: "Lunch",
    title: "Chana Masala",
    description: "Chickpeas simmered in a tangy onion-tomato masala.",
    cuisine: "Indian",
    dietary_tags: ["Vegan", "Gluten-Free"],
    time_minutes: 35,
    servings: 4,
    ingredients: [
      "2 cans (400g each) chickpeas, drained",
      "2 onions, finely diced",
      "3 tomatoes, puréed",
      "1 tbsp ginger-garlic paste",
      "1 tsp ground cumin",
      "1 tsp ground coriander",
      "1/2 tsp ground turmeric",
      "1 tsp garam masala",
      "1 tsp amchur (dried mango powder)",
      "3 tbsp oil",
    ],
    steps: [
      "Fry the onions in the oil over medium heat for 12 minutes until genuinely brown, not just soft — this is the base of the flavour.",
      "Add the ginger-garlic paste and cook until the raw smell goes.",
      "Stir in the ground spices, then the tomato purée, and cook until the oil separates at the edges.",
      "Add the chickpeas and a cup of water and simmer 15 minutes, crushing a few to thicken.",
      "Finish with garam masala and amchur.",
    ],
  },
  {
    slot: "Lunch",
    title: "Rajma Chawal",
    description:
      "North Indian red kidney bean curry with rice — proper comfort food.",
    cuisine: "Indian",
    dietary_tags: ["Vegan", "Gluten-Free"],
    time_minutes: 45,
    servings: 4,
    ingredients: [
      "2 cans (400g each) red kidney beans, drained",
      "2 onions, finely chopped",
      "3 tomatoes, puréed",
      "1 tbsp ginger-garlic paste",
      "1 tsp ground cumin",
      "1 tsp ground coriander",
      "1 tsp garam masala",
      "1/2 tsp chili powder",
      "3 tbsp oil",
      "300g basmati rice",
    ],
    steps: [
      "Brown the onions well in the oil, then add the ginger-garlic paste.",
      "Add the ground spices and tomato purée and fry until thick and glossy and the oil separates.",
      "Tip in the beans with 400ml water, then simmer 25 minutes, mashing some beans to thicken the gravy.",
      "Cook the basmati separately and serve the rajma over it, finished with garam masala.",
    ],
  },
  {
    slot: "Dinner",
    title: "Chicken Tikka Masala",
    description:
      "Charred marinated chicken in a creamy spiced tomato gravy.",
    cuisine: "Indian",
    dietary_tags: ["Gluten-Free"],
    time_minutes: 60,
    servings: 4,
    ingredients: [
      "700g chicken thighs, cubed",
      "200g plain yogurt",
      "1 tbsp ginger-garlic paste",
      "2 tsp garam masala",
      "1 tsp ground turmeric",
      "1 tsp chili powder",
      "3 tbsp ghee",
      "1 onion, finely diced",
      "1 can (400g) chopped tomatoes",
      "150ml double cream",
      "Fresh coriander",
    ],
    steps: [
      "Marinate the chicken in the yogurt, ginger-garlic paste and half the spices for at least 30 minutes.",
      "Grill or broil on a rack at high heat for 12 minutes until charred at the edges.",
      "Soften the onion in the ghee, add the remaining spices, then the tomatoes, and cook down 15 minutes.",
      "Blend the sauce smooth, return to the pan with the chicken, and simmer 10 minutes.",
      "Stir in the cream and finish with coriander.",
    ],
  },
  {
    slot: "Dinner",
    title: "Palak Paneer",
    description: "Fresh cheese cubes in a smooth, bright spinach gravy.",
    cuisine: "Indian",
    dietary_tags: ["Vegetarian", "Gluten-Free"],
    time_minutes: 40,
    servings: 4,
    ingredients: [
      "500g spinach",
      "250g paneer, cubed",
      "1 onion, diced",
      "1 tbsp ginger-garlic paste",
      "2 green chillies",
      "1 tsp ground cumin",
      "1/2 tsp garam masala",
      "3 tbsp ghee",
      "60ml cream",
    ],
    steps: [
      "Blanch the spinach for 60 seconds, then plunge into iced water — this keeps the colour bright.",
      "Blend the spinach with the chillies to a smooth purée.",
      "Fry the paneer in ghee until pale gold, then set aside.",
      "Cook the onion and ginger-garlic paste, add the cumin, then the spinach purée, and simmer 8 minutes.",
      "Return the paneer, stir in the cream and garam masala, and warm through.",
    ],
  },
  {
    slot: "Dinner",
    title: "Dal Tadka",
    description:
      "Yellow lentils finished with a hot ghee tempering poured over at the table.",
    cuisine: "Indian",
    dietary_tags: ["Vegetarian", "Gluten-Free"],
    time_minutes: 45,
    servings: 4,
    ingredients: [
      "250g toor dal (split pigeon peas)",
      "1/2 tsp ground turmeric",
      "3 tbsp ghee",
      "1 tsp cumin seeds",
      "4 cloves garlic, sliced",
      "2 dried red chillies",
      "1 tomato, diced",
      "1 pinch asafoetida",
      "Fresh coriander",
    ],
    steps: [
      "Simmer the dal with the turmeric and 1L water for 30 minutes until completely soft, then whisk to a loose purée.",
      "Heat the ghee in a small pan and add the cumin seeds until they crackle.",
      "Add the garlic, chillies and asafoetida and fry until the garlic is golden — watch it closely.",
      "Pour the sizzling tempering over the dal, stir once, and finish with tomato and coriander.",
    ],
  },

  // ------------------------------------------------------------------- Thai
  {
    slot: "Breakfast",
    title: "Jok (Thai Rice Porridge)",
    description:
      "Soft rice congee with pork meatballs, ginger and a soft egg.",
    cuisine: "Thai",
    dietary_tags: [],
    time_minutes: 45,
    servings: 2,
    ingredients: [
      "150g jasmine rice",
      "1.5L chicken stock",
      "200g minced pork",
      "1 tbsp finely grated ginger",
      "2 eggs",
      "2 spring onions, sliced",
      "1 tbsp fish sauce",
      "White pepper",
    ],
    steps: [
      "Simmer the rice in the stock for 35 minutes, stirring often, until the grains break down completely.",
      "Season the pork with a little fish sauce and pepper and roll into small balls.",
      "Drop the meatballs into the porridge and cook 5 minutes until firm.",
      "Crack an egg into each bowl, ladle the very hot jok over to just set it, and top with ginger and spring onion.",
    ],
  },
  {
    slot: "Breakfast",
    title: "Khai Jiao",
    description:
      "Thai omelette deep-fried until puffed and crisp, served over rice.",
    cuisine: "Thai",
    dietary_tags: ["Gluten-Free", "Dairy-Free"],
    time_minutes: 15,
    servings: 2,
    ingredients: [
      "4 eggs",
      "1 tbsp fish sauce",
      "1 tsp lime juice",
      "6 tbsp vegetable oil",
      "2 cups cooked jasmine rice",
      "Sriracha, to serve",
    ],
    steps: [
      "Beat the eggs hard with the fish sauce and lime until frothy — the air is what makes it puff.",
      "Heat the oil in a wok until it shimmers and a drop of egg sizzles instantly.",
      "Pour the egg in from a height in one go; it should billow up at once.",
      "Fry 90 seconds, flip, and cook 45 seconds more until crisp. Drain and serve over rice with sriracha.",
    ],
  },
  {
    slot: "Lunch",
    title: "Tom Yum Goong",
    description:
      "Hot and sour prawn soup with lemongrass, galangal and lime leaf.",
    cuisine: "Thai",
    dietary_tags: ["Gluten-Free", "Dairy-Free", "Pescatarian"],
    time_minutes: 30,
    servings: 2,
    ingredients: [
      "300g raw prawns, shells reserved",
      "1L prawn or fish stock",
      "2 stalks lemongrass, bruised",
      "4 slices galangal",
      "4 kaffir lime leaves, torn",
      "150g oyster mushrooms",
      "3 tbsp fish sauce",
      "3 tbsp lime juice",
      "4 bird's eye chillies, crushed",
      "1 tbsp nam prik pao (chili paste)",
    ],
    steps: [
      "Simmer the prawn shells in the stock for 10 minutes, then strain them out.",
      "Add the lemongrass, galangal and lime leaves and infuse 5 minutes without boiling hard.",
      "Add the mushrooms and prawns and cook 3 minutes until the prawns just turn opaque.",
      "Take off the heat before adding the fish sauce, lime juice, chillies and chili paste — boiling lime juice dulls it.",
    ],
  },
  {
    slot: "Lunch",
    title: "Larb Gai",
    description:
      "Minced chicken salad with toasted rice powder, lime and herbs, from Isan.",
    cuisine: "Thai",
    dietary_tags: ["Gluten-Free", "Dairy-Free"],
    time_minutes: 25,
    servings: 2,
    ingredients: [
      "400g minced chicken",
      "3 tbsp lime juice",
      "2 tbsp fish sauce",
      "1 tbsp toasted rice powder (khao khua)",
      "1 tsp chili flakes",
      "3 shallots, thinly sliced",
      "1 handful mint leaves",
      "1 handful coriander",
      "Lettuce leaves and sticky rice, to serve",
    ],
    steps: [
      "Cook the chicken in a splash of water over high heat, breaking it up, until just cooked; do not brown it.",
      "Take off the heat and dress at once with the lime juice and fish sauce while warm.",
      "Fold through the rice powder, chili flakes and shallots.",
      "Add the herbs last so they stay fresh, and serve with lettuce and sticky rice.",
    ],
  },
  {
    slot: "Dinner",
    title: "Gaeng Keow Wan (Green Curry)",
    description:
      "Coconut green curry with chicken, aubergine and Thai basil.",
    cuisine: "Thai",
    dietary_tags: ["Gluten-Free", "Dairy-Free"],
    time_minutes: 35,
    servings: 4,
    ingredients: [
      "3 tbsp green curry paste",
      "400ml coconut milk (not shaken)",
      "500g chicken thigh, sliced",
      "150g Thai aubergines, quartered",
      "2 tbsp fish sauce",
      "1 tbsp palm sugar",
      "4 kaffir lime leaves",
      "1 handful Thai basil",
      "1 red chilli, sliced",
    ],
    steps: [
      "Spoon the thick cream from the top of the coconut milk into a hot pan and fry the paste in it until it splits and smells fragrant.",
      "Add the chicken and coat well in the paste, cooking 3 minutes.",
      "Pour in the rest of the coconut milk with the aubergines and simmer 12 minutes.",
      "Season with fish sauce and palm sugar, add the lime leaves, then stir the basil through off the heat.",
    ],
  },
  {
    slot: "Dinner",
    title: "Pad See Ew",
    description:
      "Wide rice noodles charred in dark soy with Chinese broccoli and egg.",
    cuisine: "Thai",
    dietary_tags: ["Vegetarian"],
    time_minutes: 25,
    servings: 2,
    ingredients: [
      "400g fresh wide rice noodles",
      "200g Chinese broccoli, stems sliced",
      "2 eggs",
      "3 tbsp dark soy sauce",
      "1 tbsp light soy sauce",
      "1 tbsp sugar",
      "1 tbsp rice vinegar",
      "3 cloves garlic, minced",
      "3 tbsp oil",
    ],
    steps: [
      "Get the wok as hot as it will go — the char is the whole point of this dish.",
      "Fry the garlic briefly, add the noodles and dark soy, and leave them undisturbed 30 seconds at a time to catch.",
      "Push aside, scramble the eggs in the space, then combine.",
      "Add the Chinese broccoli, light soy, sugar and vinegar and toss until the stems are just tender.",
    ],
  },

  // ------------------------------------------------------------- Vietnamese
  {
    slot: "Breakfast",
    title: "Phở Bò",
    description:
      "Clear beef broth simmered with charred aromatics, poured over rice noodles.",
    cuisine: "Vietnamese",
    dietary_tags: ["Dairy-Free"],
    time_minutes: 180,
    servings: 4,
    ingredients: [
      "1.5kg beef bones",
      "300g beef brisket",
      "1 onion, halved",
      "1 thumb ginger, halved",
      "4 star anise",
      "1 cinnamon stick",
      "4 cloves",
      "3 tbsp fish sauce",
      "400g flat rice noodles",
      "200g beef sirloin, sliced paper-thin",
      "Thai basil, beansprouts, lime and chilli, to serve",
    ],
    steps: [
      "Blanch the bones in boiling water for 5 minutes, then rinse them and the pot — this is what keeps the broth clear.",
      "Char the onion and ginger directly over a flame until blackened in patches.",
      "Simmer the bones, brisket, charred aromatics and toasted spices in 4L water for 2.5 hours, skimming often. Never let it boil hard.",
      "Strain, season with fish sauce, and keep at a rolling simmer.",
      "Divide cooked noodles into bowls, lay the raw sirloin on top, and ladle the boiling broth over to cook it. Serve with the herb plate.",
    ],
  },
  {
    slot: "Breakfast",
    title: "Bánh Cuốn",
    description:
      "Delicate steamed rice sheets rolled around minced pork and wood ear mushroom.",
    cuisine: "Vietnamese",
    dietary_tags: ["Dairy-Free"],
    time_minutes: 60,
    servings: 4,
    ingredients: [
      "200g rice flour",
      "50g tapioca starch",
      "600ml water",
      "250g minced pork",
      "30g dried wood ear mushrooms, soaked and chopped",
      "2 shallots, minced",
      "3 tbsp fish sauce",
      "1 tbsp sugar",
      "1 lime, juiced",
      "Crispy fried shallots, to serve",
    ],
    steps: [
      "Whisk the flours with the water and a pinch of salt into a thin batter and rest 30 minutes.",
      "Fry the shallots, pork and wood ear with a splash of fish sauce until cooked; season.",
      "Ladle a thin layer of batter into a hot oiled non-stick pan, cover, and steam 40 seconds until translucent.",
      "Slide out, spoon filling along one edge, and roll up.",
      "Mix the remaining fish sauce with the sugar, lime and water for the dipping sauce, and top the rolls with fried shallots.",
    ],
  },
  {
    slot: "Lunch",
    title: "Bánh Mì Thịt",
    description:
      "Airy baguette with pâté, pork, pickled carrot and daikon, chilli and coriander.",
    cuisine: "Vietnamese",
    dietary_tags: [],
    time_minutes: 30,
    servings: 2,
    ingredients: [
      "2 short Vietnamese baguettes",
      "120g pork pâté",
      "200g roast pork or cold cuts",
      "1 carrot, julienned",
      "150g daikon, julienned",
      "3 tbsp rice vinegar",
      "2 tbsp sugar",
      "1/2 cucumber, in batons",
      "2 tbsp mayonnaise",
      "1 red chilli, sliced",
      "Fresh coriander",
    ],
    steps: [
      "Toss the carrot and daikon with the vinegar, sugar and a pinch of salt and leave 20 minutes to pickle.",
      "Warm the baguettes until the crust crackles, then split and pull out a little of the crumb.",
      "Spread with mayonnaise and pâté right to the edges.",
      "Fill with the pork, drained pickles, cucumber, chilli and plenty of coriander.",
    ],
  },
  {
    slot: "Lunch",
    title: "Gỏi Cuốn",
    description:
      "Fresh rice paper rolls with prawn, herbs and vermicelli, with peanut sauce.",
    cuisine: "Vietnamese",
    dietary_tags: ["Dairy-Free", "Pescatarian"],
    time_minutes: 35,
    servings: 2,
    ingredients: [
      "12 sheets rice paper",
      "200g cooked prawns, halved lengthways",
      "100g rice vermicelli, cooked",
      "1 head butter lettuce",
      "1 handful mint",
      "1 handful coriander",
      "3 tbsp hoisin sauce",
      "2 tbsp peanut butter",
      "1 tbsp crushed peanuts",
    ],
    steps: [
      "Dip a rice paper sheet in warm water for 2 seconds only — it keeps softening as you work.",
      "Lay the prawns cut-side up near the top so they show through, then add lettuce, vermicelli and herbs below.",
      "Fold the bottom up, fold the sides in, and roll tightly.",
      "Warm the hoisin and peanut butter with a splash of water into a dipping sauce and top with crushed peanuts.",
    ],
  },
  {
    slot: "Dinner",
    title: "Bún Chả",
    description:
      "Hanoi grilled pork patties and belly served in a sweet-sour dipping broth with noodles.",
    cuisine: "Vietnamese",
    dietary_tags: ["Dairy-Free"],
    time_minutes: 50,
    servings: 4,
    ingredients: [
      "400g minced pork",
      "300g pork belly, thinly sliced",
      "4 tbsp fish sauce",
      "3 tbsp sugar",
      "3 cloves garlic, minced",
      "2 shallots, minced",
      "4 tbsp rice vinegar",
      "1 carrot, thinly sliced",
      "400g rice vermicelli, cooked",
      "Lettuce and herbs, to serve",
    ],
    steps: [
      "Marinate the mince and belly separately with half the fish sauce, sugar, garlic and shallots for 30 minutes.",
      "Shape the mince into small flat patties.",
      "Grill the patties and belly over high heat until well charred at the edges.",
      "Mix the remaining fish sauce, sugar, vinegar and 300ml warm water into a light dipping broth and add the carrot.",
      "Drop the hot grilled pork into the broth and serve with noodles and herbs alongside.",
    ],
  },
  {
    slot: "Dinner",
    title: "Thịt Kho Trứng",
    description:
      "Pork belly and eggs braised in caramel and coconut water until glossy.",
    cuisine: "Vietnamese",
    dietary_tags: ["Dairy-Free"],
    time_minutes: 90,
    servings: 4,
    ingredients: [
      "800g pork belly, in large cubes",
      "6 eggs, boiled and peeled",
      "3 tbsp sugar",
      "4 tbsp fish sauce",
      "500ml coconut water",
      "4 cloves garlic, minced",
      "2 shallots, minced",
      "Black pepper",
    ],
    steps: [
      "Melt the sugar in a dry pan until it turns amber — take it off just before it smells bitter.",
      "Add the shallots, garlic and pork and turn to coat in the caramel.",
      "Pour in the coconut water and fish sauce, bring to a simmer, and skim.",
      "Add the eggs and braise gently, uncovered, for 60 minutes until the pork is tender and the sauce is syrupy.",
    ],
  },

  // ---------------------------------------------------------------- Chinese
  {
    slot: "Breakfast",
    title: "Ginger and Scallion Congee",
    description: "Rice simmered to a silky porridge with ginger and spring onion.",
    cuisine: "Chinese",
    dietary_tags: ["Vegan"],
    time_minutes: 60,
    servings: 2,
    ingredients: [
      "150g jasmine rice",
      "1.5L vegetable stock",
      "1 thumb ginger, julienned",
      "3 spring onions, sliced",
      "2 tbsp crispy fried shallots",
      "1 tsp sesame oil",
      "Light soy sauce, to taste",
    ],
    steps: [
      "Rinse the rice, then freeze it for 20 minutes if you have time — the cracked grains break down faster.",
      "Simmer the rice and stock with half the ginger for 45-50 minutes, stirring often, until thick and creamy.",
      "Season with soy sauce; it should be savoury but still mild.",
      "Top with the remaining ginger, spring onion, fried shallots and sesame oil.",
    ],
  },
  {
    slot: "Breakfast",
    title: "Jianbing",
    description:
      "Beijing street crepe with egg, crisp cracker, hoisin and coriander.",
    cuisine: "Chinese",
    dietary_tags: ["Vegetarian"],
    time_minutes: 25,
    servings: 2,
    ingredients: [
      "100g plain flour",
      "40g mung bean flour",
      "300ml water",
      "4 eggs",
      "2 sheets crisp wonton cracker",
      "3 tbsp hoisin sauce",
      "1 tbsp chili sauce",
      "3 spring onions, sliced",
      "Fresh coriander",
    ],
    steps: [
      "Whisk the flours and water into a thin, lump-free batter.",
      "Spread a ladleful very thin on a hot oiled flat pan using a circular motion.",
      "Crack two eggs on top and spread them over the surface before the crepe sets.",
      "Brush with hoisin and chili sauce, scatter spring onion and coriander, add the cracker, then fold into quarters.",
    ],
  },
  {
    slot: "Lunch",
    title: "Dan Dan Noodles",
    description:
      "Sichuan noodles with chili oil, sesame paste and crisp minced pork.",
    cuisine: "Chinese",
    dietary_tags: [],
    time_minutes: 30,
    servings: 2,
    ingredients: [
      "250g wheat noodles",
      "200g minced pork",
      "2 tbsp preserved mustard greens (ya cai)",
      "3 tbsp Chinese sesame paste",
      "3 tbsp chili oil with sediment",
      "2 tbsp light soy sauce",
      "1 tsp ground Sichuan pepper",
      "1 tsp black vinegar",
      "2 spring onions, sliced",
    ],
    steps: [
      "Fry the pork hard until dry and crisp, then add the preserved greens and cook 2 minutes.",
      "Whisk the sesame paste, chili oil, soy, vinegar and Sichuan pepper in the base of each bowl.",
      "Cook the noodles, then lift them straight into the bowls with a little starchy cooking water.",
      "Top with the pork and spring onion, and toss thoroughly at the table before eating.",
    ],
  },
  {
    slot: "Lunch",
    title: "Wonton Noodle Soup",
    description: "Prawn and pork wontons in a clear broth with egg noodles.",
    cuisine: "Chinese",
    dietary_tags: [],
    time_minutes: 45,
    servings: 4,
    ingredients: [
      "30 wonton wrappers",
      "200g minced pork",
      "150g raw prawns, chopped",
      "1 tbsp light soy sauce",
      "1 tsp sesame oil",
      "1 tsp grated ginger",
      "1.5L chicken stock",
      "300g thin egg noodles",
      "200g choy sum",
      "2 spring onions, sliced",
    ],
    steps: [
      "Mix the pork, prawns, soy, sesame oil and ginger and beat in one direction until sticky.",
      "Place a teaspoon of filling on each wrapper, wet the edge, and gather into a loose purse.",
      "Bring the stock to a gentle simmer and season it.",
      "Boil the wontons in a separate pan of water for 4 minutes until they float and the wrappers turn translucent.",
      "Cook the noodles and greens, then assemble in bowls and ladle the hot stock over.",
    ],
  },
  {
    slot: "Dinner",
    title: "Mapo Tofu",
    description:
      "Sichuan silken tofu in a numbing chili bean sauce with minced beef.",
    cuisine: "Chinese",
    dietary_tags: [],
    time_minutes: 25,
    servings: 2,
    ingredients: [
      "400g silken tofu, cubed",
      "150g minced beef",
      "2 tbsp doubanjiang (fermented chili bean paste)",
      "1 tbsp fermented black beans, rinsed",
      "1 tsp ground Sichuan pepper",
      "300ml chicken stock",
      "1 tbsp cornflour, slaked in water",
      "3 spring onions, sliced",
      "3 tbsp oil",
    ],
    steps: [
      "Slide the tofu into lightly salted simmering water for 2 minutes, then drain — this firms it so it holds together.",
      "Fry the beef until browned, then add the doubanjiang and black beans and cook until the oil turns red.",
      "Add the stock and bring to a simmer, then slide in the tofu and push it gently rather than stirring.",
      "Thicken with the cornflour slurry in two additions, then finish with Sichuan pepper and spring onion.",
    ],
  },
  {
    slot: "Dinner",
    title: "Kung Pao Chicken",
    description:
      "Diced chicken with dried chillies, peanuts and a sweet-sour Sichuan sauce.",
    cuisine: "Chinese",
    dietary_tags: ["Dairy-Free"],
    time_minutes: 30,
    servings: 2,
    ingredients: [
      "400g chicken thigh, diced",
      "1 tbsp cornflour",
      "10 dried red chillies, halved",
      "1 tsp Sichuan peppercorns",
      "60g roasted peanuts",
      "2 tbsp light soy sauce",
      "1 tbsp black vinegar",
      "1 tbsp sugar",
      "3 spring onions, in short lengths",
      "3 tbsp oil",
    ],
    steps: [
      "Toss the chicken with the cornflour and a splash of soy and rest 15 minutes.",
      "Mix the remaining soy, vinegar and sugar into a sauce and set it by the hob.",
      "Fry the chillies and peppercorns in oil briefly until fragrant but not black.",
      "Add the chicken in a single layer, leave to colour, then stir-fry until cooked.",
      "Pour in the sauce, toss until it clings, then add the peanuts and spring onion off the heat.",
    ],
  },

  // --------------------------------------------------------------- Japanese
  {
    slot: "Breakfast",
    title: "Tamagoyaki with Rice and Miso",
    description:
      "Rolled sweet-savoury omelette with steamed rice and miso soup.",
    cuisine: "Japanese",
    dietary_tags: [],
    time_minutes: 25,
    servings: 2,
    ingredients: [
      "4 eggs",
      "1 tbsp mirin",
      "1 tsp soy sauce",
      "1 tsp sugar",
      "Neutral oil, for the pan",
      "2 cups steamed short-grain rice",
      "500ml dashi",
      "2 tbsp miso paste",
      "1 spring onion, sliced",
    ],
    steps: [
      "Beat the eggs with the mirin, soy and sugar and strain for a smooth texture.",
      "Oil a rectangular pan over medium-low heat, pour in a thin layer, and roll it to one side as it sets.",
      "Oil again, add more egg, lifting the roll so the raw egg runs underneath, and roll back. Repeat until used up.",
      "Warm the dashi and whisk in the miso off the boil, then add the spring onion.",
      "Slice the omelette and serve with rice and the miso soup.",
    ],
  },
  {
    slot: "Breakfast",
    title: "Onigiri",
    description: "Salted rice balls wrapped in nori with a savoury filling.",
    cuisine: "Japanese",
    dietary_tags: ["Pescatarian"],
    time_minutes: 20,
    servings: 2,
    ingredients: [
      "3 cups cooked short-grain rice, warm",
      "1 tsp fine salt",
      "100g cooked salmon flakes",
      "1 tbsp Japanese mayonnaise",
      "2 sheets nori, cut into strips",
      "1 tbsp toasted sesame seeds",
    ],
    steps: [
      "Mix the salmon with the mayonnaise.",
      "Wet your hands and rub them with salt, then take a handful of warm rice.",
      "Press a dent into the rice, add filling, and close the rice over it.",
      "Shape into a firm triangle with light, even pressure, then wrap with nori just before eating so it stays crisp.",
    ],
  },
  {
    slot: "Lunch",
    title: "Miso Ramen",
    description: "Rich miso broth with springy noodles, corn and a soft egg.",
    cuisine: "Japanese",
    dietary_tags: [],
    time_minutes: 40,
    servings: 2,
    ingredients: [
      "2 portions fresh ramen noodles",
      "1L chicken stock",
      "3 tbsp miso paste",
      "1 tbsp toasted sesame paste",
      "1 tbsp soy sauce",
      "2 eggs",
      "100g sweetcorn",
      "2 spring onions, sliced",
      "1 tsp chili oil",
    ],
    steps: [
      "Boil the eggs for exactly 6 minutes 30 seconds, then chill in iced water and peel.",
      "Warm the stock and whisk in the miso and sesame paste off the boil so the miso keeps its aroma.",
      "Cook the noodles separately and drain them well — starchy water clouds the broth.",
      "Assemble with the broth, noodles, halved eggs, corn, spring onion and chili oil.",
    ],
  },
  {
    slot: "Lunch",
    title: "Chicken Katsu Curry",
    description:
      "Panko-crumbed chicken with a thick, mildly sweet Japanese curry sauce.",
    cuisine: "Japanese",
    dietary_tags: [],
    time_minutes: 45,
    servings: 2,
    ingredients: [
      "2 chicken breasts, butterflied",
      "80g panko breadcrumbs",
      "1 egg, beaten",
      "3 tbsp plain flour",
      "1 onion, sliced",
      "1 carrot, chopped",
      "2 tbsp curry powder",
      "1 tbsp plain flour, for the sauce",
      "500ml chicken stock",
      "1 tsp honey",
      "2 cups cooked rice",
      "Oil, for frying",
    ],
    steps: [
      "Soften the onion and carrot, stir in the curry powder and flour, then whisk in the stock.",
      "Simmer 20 minutes until thick enough to coat a spoon, add the honey, and blend smooth if you prefer.",
      "Coat the chicken in flour, then egg, then panko, pressing the crumbs on firmly.",
      "Shallow-fry for 4 minutes per side until deep gold and cooked through; drain and slice.",
      "Serve over rice with the sauce poured alongside so the crust stays crisp.",
    ],
  },
  {
    slot: "Dinner",
    title: "Gyudon",
    description:
      "Beef and onion simmered in sweet soy dashi and spooned over rice.",
    cuisine: "Japanese",
    dietary_tags: ["Dairy-Free"],
    time_minutes: 25,
    servings: 2,
    ingredients: [
      "300g beef sirloin, sliced paper-thin",
      "1 onion, sliced",
      "200ml dashi",
      "3 tbsp soy sauce",
      "2 tbsp mirin",
      "1 tbsp sugar",
      "2 cups cooked short-grain rice",
      "1 spring onion, sliced",
      "Pickled ginger, to serve",
    ],
    steps: [
      "Simmer the dashi, soy, mirin and sugar with the onion for 5 minutes until the onion softens.",
      "Add the beef in loose handfuls and cook just until it loses its pink, about 2 minutes.",
      "Skim any foam so the sauce stays clean-tasting.",
      "Spoon the beef and some broth over hot rice and top with spring onion and pickled ginger.",
    ],
  },
  {
    slot: "Dinner",
    title: "Salmon Shioyaki",
    description:
      "Salt-grilled salmon with crisp skin, served with rice and greens.",
    cuisine: "Japanese",
    dietary_tags: ["Gluten-Free", "Dairy-Free", "Pescatarian"],
    time_minutes: 40,
    servings: 2,
    ingredients: [
      "2 salmon fillets, skin on",
      "2 tsp fine sea salt",
      "1 tbsp sake",
      "2 cups cooked short-grain rice",
      "200g spinach, blanched",
      "1 tsp tamari (gluten-free soy sauce)",
      "1 lemon, in wedges",
    ],
    steps: [
      "Salt the salmon on both sides and leave uncovered in the fridge for 20 minutes, then pat away the moisture that beads up.",
      "Brush with sake and grill skin-side up under high heat for 6 minutes.",
      "Turn and grill 3 minutes more until just opaque at the thickest point.",
      "Dress the spinach with the tamari and serve with rice and lemon.",
    ],
  },

  // ----------------------------------------------------------------- Korean
  {
    slot: "Breakfast",
    title: "Gyeran Bap",
    description:
      "Hot rice with a fried egg, sesame oil and soy — the fastest Korean breakfast.",
    cuisine: "Korean",
    dietary_tags: ["Vegetarian"],
    time_minutes: 10,
    servings: 1,
    ingredients: [
      "1.5 cups hot cooked short-grain rice",
      "2 eggs",
      "1 tbsp toasted sesame oil",
      "1 tbsp soy sauce",
      "1 sheet gim (roasted seaweed), crumbled",
      "1 tsp toasted sesame seeds",
      "1 spring onion, sliced",
    ],
    steps: [
      "Fry the eggs in a little oil over high heat until the whites are crisp at the edges and the yolks still run.",
      "Put the hot rice in a bowl and pour the sesame oil and soy over it.",
      "Slide the eggs on top and break the yolks into the rice.",
      "Finish with crumbled gim, sesame seeds and spring onion, and mix well before eating.",
    ],
  },
  {
    slot: "Breakfast",
    title: "Kongnamul Gukbap",
    description:
      "Clear soybean sprout soup poured over rice — light and restorative.",
    cuisine: "Korean",
    dietary_tags: ["Vegan"],
    time_minutes: 30,
    servings: 2,
    ingredients: [
      "300g soybean sprouts",
      "1.2L water",
      "1 piece dried kelp (dasima)",
      "3 cloves garlic, minced",
      "1 tbsp soup soy sauce",
      "2 spring onions, sliced",
      "1 tsp gochugaru (chili flakes)",
      "2 cups cooked rice",
    ],
    steps: [
      "Simmer the kelp in the water for 10 minutes, then remove it.",
      "Add the sprouts and cook 8 minutes with the lid ON the whole time — lifting it mid-cook makes them smell raw.",
      "Season with the garlic and soup soy sauce.",
      "Ladle over rice in bowls and finish with spring onion and gochugaru.",
    ],
  },
  {
    slot: "Lunch",
    title: "Kimchi Jjigae",
    description:
      "Sour aged kimchi stewed with pork belly and tofu — better the older the kimchi.",
    cuisine: "Korean",
    dietary_tags: [],
    time_minutes: 35,
    servings: 2,
    ingredients: [
      "300g well-fermented kimchi, chopped",
      "200g pork belly, sliced",
      "200g firm tofu, sliced",
      "1 tbsp gochujang",
      "1 tbsp gochugaru",
      "500ml water or anchovy stock",
      "1 tsp sugar",
      "2 spring onions, sliced",
      "1 tsp sesame oil",
    ],
    steps: [
      "Fry the pork belly in the sesame oil until the fat renders and the edges brown.",
      "Add the kimchi and its juice and stir-fry 5 minutes — cooking it first deepens the sourness.",
      "Add the gochujang, gochugaru, sugar and stock and simmer 15 minutes.",
      "Lay the tofu on top and simmer 5 minutes more, then scatter with spring onion.",
    ],
  },
  {
    slot: "Lunch",
    title: "Bibim Guksu",
    description:
      "Cold wheat noodles tossed in a sweet, sharp gochujang sauce.",
    cuisine: "Korean",
    dietary_tags: ["Vegetarian"],
    time_minutes: 20,
    servings: 2,
    ingredients: [
      "200g somyeon (thin wheat noodles)",
      "3 tbsp gochujang",
      "1 tbsp gochugaru",
      "2 tbsp rice vinegar",
      "1 tbsp sugar",
      "1 tbsp sesame oil",
      "2 cloves garlic, minced",
      "1/2 cucumber, julienned",
      "2 eggs, boiled and halved",
      "1 tbsp sesame seeds",
    ],
    steps: [
      "Whisk the gochujang, gochugaru, vinegar, sugar, sesame oil and garlic into a sauce.",
      "Boil the noodles for 3 minutes, then rinse under cold running water, rubbing them, until completely cold.",
      "Drain very well — any water left will dilute the sauce.",
      "Toss the noodles with the sauce and top with cucumber, egg and sesame seeds.",
    ],
  },
  {
    slot: "Dinner",
    title: "Bibimbap",
    description:
      "Rice bowl arranged with seasoned vegetables, beef and a fried egg.",
    cuisine: "Korean",
    dietary_tags: [],
    time_minutes: 45,
    servings: 2,
    ingredients: [
      "2 cups cooked short-grain rice",
      "200g minced beef",
      "1 carrot, julienned",
      "1 courgette, julienned",
      "150g spinach",
      "150g soybean sprouts",
      "2 eggs",
      "3 tbsp gochujang",
      "2 tbsp sesame oil",
      "2 tbsp soy sauce",
      "1 tbsp sesame seeds",
    ],
    steps: [
      "Season the beef with soy and a little sesame oil and fry until browned.",
      "Cook each vegetable separately and dress each with a pinch of salt and sesame oil — cooking them together muddies the flavours.",
      "Fry the eggs sunny side up.",
      "Arrange the rice in bowls with the vegetables and beef in separate sections and the egg in the middle.",
      "Serve with gochujang and sesame seeds, and mix thoroughly before eating.",
    ],
  },
  {
    slot: "Dinner",
    title: "Bulgogi",
    description:
      "Thin beef marinated in soy, pear and sesame, seared fast over high heat.",
    cuisine: "Korean",
    dietary_tags: ["Dairy-Free"],
    time_minutes: 40,
    servings: 4,
    ingredients: [
      "700g beef sirloin, sliced paper-thin",
      "1/2 Asian pear, grated",
      "5 tbsp soy sauce",
      "2 tbsp sugar",
      "2 tbsp sesame oil",
      "4 cloves garlic, minced",
      "1 onion, sliced",
      "3 spring onions, in lengths",
      "1 tbsp sesame seeds",
      "Lettuce leaves, to serve",
    ],
    steps: [
      "Mix the grated pear, soy, sugar, sesame oil and garlic; the pear enzymes tenderise the beef.",
      "Marinate the beef for at least 30 minutes, but no more than 2 hours or it turns mushy.",
      "Sear in a very hot pan in batches so the meat caramelises rather than steams.",
      "Add the onion and spring onion for the last minute, then serve with lettuce for wrapping.",
    ],
  },

  // ---------------------------------------------------------------- Mexican
  {
    slot: "Breakfast",
    title: "Huevos Rancheros",
    description:
      "Fried eggs on lightly crisped tortillas with a cooked salsa and beans.",
    cuisine: "Mexican",
    dietary_tags: ["Vegetarian", "Gluten-Free"],
    time_minutes: 30,
    servings: 2,
    ingredients: [
      "4 corn tortillas",
      "4 eggs",
      "4 tomatoes, chopped",
      "1 white onion, diced",
      "2 serrano chillies, chopped",
      "2 cloves garlic",
      "250g refried black beans",
      "60g queso fresco, crumbled",
      "3 tbsp oil",
      "Fresh coriander",
    ],
    steps: [
      "Char the tomatoes, chillies, garlic and half the onion in a dry pan until blackened in patches.",
      "Blend to a salsa, then fry it in a little hot oil for 5 minutes to concentrate it — this step is what makes it ranchera.",
      "Warm the beans and crisp the tortillas briefly in oil.",
      "Fry the eggs, set them on the tortillas, and spoon the hot salsa around the yolks.",
      "Top with queso fresco, the remaining onion and coriander.",
    ],
  },
  {
    slot: "Breakfast",
    title: "Chilaquiles Verdes",
    description:
      "Tortilla chips simmered briefly in salsa verde with crema and onion.",
    cuisine: "Mexican",
    dietary_tags: ["Vegetarian", "Gluten-Free"],
    time_minutes: 25,
    servings: 2,
    ingredients: [
      "200g thick tortilla chips (totopos)",
      "500g tomatillos, husked",
      "2 jalapeños",
      "1/2 white onion",
      "2 cloves garlic",
      "1 bunch coriander",
      "3 tbsp crema",
      "60g queso fresco",
      "2 eggs, fried",
    ],
    steps: [
      "Boil the tomatillos, jalapeños, onion and garlic for 8 minutes until the tomatillos turn olive-green.",
      "Blend with the coriander and season; fry the salsa in a little oil for 5 minutes.",
      "Fold the totopos through the hot salsa and serve within a minute — leave them longer and they go soggy.",
      "Top with crema, queso fresco, sliced onion and a fried egg.",
    ],
  },
  {
    slot: "Lunch",
    title: "Tacos al Pastor",
    description:
      "Chili-marinated pork with pineapple, in the style of the trompo.",
    cuisine: "Mexican",
    dietary_tags: ["Gluten-Free", "Dairy-Free"],
    time_minutes: 60,
    servings: 4,
    ingredients: [
      "700g pork shoulder, thinly sliced",
      "3 guajillo chillies, soaked",
      "2 ancho chillies, soaked",
      "1 tbsp achiote paste",
      "3 tbsp pineapple juice",
      "2 tbsp white vinegar",
      "3 cloves garlic",
      "1 tsp dried oregano",
      "200g fresh pineapple, diced",
      "12 corn tortillas",
      "1 white onion, diced",
      "Fresh coriander",
    ],
    steps: [
      "Blend the soaked chillies with the achiote, pineapple juice, vinegar, garlic and oregano into a marinade.",
      "Marinate the pork for at least 2 hours, ideally overnight.",
      "Sear in a very hot pan in batches until charred at the edges, then chop finely.",
      "Char the pineapple in the same pan.",
      "Serve on warm tortillas with pineapple, onion and coriander.",
    ],
  },
  {
    slot: "Lunch",
    title: "Quesadillas de Frijol",
    description: "Corn tortillas folded over melted cheese and black beans.",
    cuisine: "Mexican",
    dietary_tags: ["Vegetarian", "Gluten-Free"],
    time_minutes: 20,
    servings: 2,
    ingredients: [
      "6 corn tortillas",
      "200g Oaxaca cheese, pulled apart",
      "200g black beans, lightly mashed",
      "1/2 tsp ground cumin",
      "1 avocado, sliced",
      "Salsa verde, to serve",
    ],
    steps: [
      "Season the mashed beans with the cumin and a pinch of salt.",
      "Warm a dry comal or heavy pan over medium heat.",
      "Lay a tortilla down, cover half with cheese and beans, and fold over as the cheese starts to melt.",
      "Press and cook 2 minutes per side until the tortilla blisters and the cheese pulls.",
      "Serve with avocado and salsa verde.",
    ],
  },
  {
    slot: "Dinner",
    title: "Tacos de Pescado",
    description:
      "Baja-style battered fish tacos with cabbage and a lime crema.",
    cuisine: "Mexican",
    dietary_tags: ["Pescatarian"],
    time_minutes: 40,
    servings: 4,
    ingredients: [
      "600g white fish fillets, in strips",
      "120g plain flour",
      "180ml cold beer",
      "1 tsp baking powder",
      "Oil, for frying",
      "12 corn tortillas",
      "300g white cabbage, shredded",
      "4 tbsp mayonnaise",
      "3 tbsp crema",
      "2 limes",
    ],
    steps: [
      "Whisk the flour, baking powder and cold beer into a batter the thickness of double cream and rest 10 minutes.",
      "Heat the oil to 180°C.",
      "Mix the mayonnaise, crema and the juice of one lime, then toss a little through the cabbage.",
      "Dip the fish in the batter and fry 3-4 minutes until crisp and pale gold; drain on a rack, not paper.",
      "Serve in warm tortillas with cabbage, more crema and lime wedges.",
    ],
  },
  {
    slot: "Dinner",
    title: "Enchiladas Verdes",
    description:
      "Rolled tortillas filled with chicken under a tangy tomatillo sauce.",
    cuisine: "Mexican",
    dietary_tags: ["Gluten-Free"],
    time_minutes: 50,
    servings: 4,
    ingredients: [
      "12 corn tortillas",
      "500g cooked chicken, shredded",
      "700g tomatillos, husked",
      "3 jalapeños",
      "1/2 white onion",
      "3 cloves garlic",
      "1 bunch coriander",
      "200g Monterey Jack, grated",
      "150ml crema",
      "3 tbsp oil",
    ],
    steps: [
      "Boil the tomatillos, jalapeños, onion and garlic for 8 minutes, then blend with the coriander.",
      "Fry the sauce in hot oil for 5 minutes and season.",
      "Dip each tortilla briefly in warm oil to soften it so it will roll without cracking.",
      "Fill with chicken, roll, and pack seam-down in a dish.",
      "Cover with the sauce and cheese and bake at 190°C for 20 minutes, then finish with crema.",
    ],
  },

  // --------------------------------------------------------------- American
  {
    slot: "Breakfast",
    title: "Buttermilk Pancakes",
    description: "Tall, tender stack with butter and maple syrup.",
    cuisine: "American",
    dietary_tags: ["Vegetarian"],
    time_minutes: 25,
    servings: 4,
    ingredients: [
      "250g plain flour",
      "2 tbsp caster sugar",
      "2 tsp baking powder",
      "1/2 tsp bicarbonate of soda",
      "1/2 tsp salt",
      "400ml buttermilk",
      "2 eggs",
      "50g melted butter",
      "Maple syrup, to serve",
    ],
    steps: [
      "Whisk the dry ingredients together in a large bowl.",
      "Beat the buttermilk, eggs and melted butter, then fold into the dry mix until just combined — lumps are fine and overmixing makes them tough.",
      "Rest the batter 10 minutes so the raising agents activate.",
      "Cook ladlefuls on a buttered griddle over medium heat until bubbles break the surface, then flip and cook 1 minute more.",
    ],
  },
  {
    slot: "Breakfast",
    title: "Overnight Oats with Berries",
    description: "No-cook oats soaked with chia and topped with fresh fruit.",
    cuisine: "American",
    dietary_tags: ["Vegan"],
    time_minutes: 10,
    servings: 1,
    ingredients: [
      "60g rolled oats",
      "180ml oat milk",
      "1 tbsp chia seeds",
      "1 tsp maple syrup",
      "80g mixed berries",
      "1 tbsp almond butter",
    ],
    steps: [
      "Stir the oats, oat milk, chia and maple syrup together in a jar.",
      "Cover and refrigerate overnight, or at least 4 hours.",
      "Loosen with a splash more milk in the morning if it has set too firm.",
      "Top with the berries and almond butter.",
    ],
  },
  {
    slot: "Lunch",
    title: "Chicken Caesar Salad",
    description: "Crisp romaine, grilled chicken, parmesan and a garlicky dressing.",
    cuisine: "American",
    dietary_tags: [],
    time_minutes: 25,
    servings: 2,
    ingredients: [
      "2 chicken breasts",
      "2 romaine hearts, chopped",
      "80g croutons",
      "40g parmesan, shaved",
      "1 egg yolk",
      "4 anchovy fillets",
      "1 clove garlic",
      "1 tsp Dijon mustard",
      "1 lemon, juiced",
      "100ml olive oil",
    ],
    steps: [
      "Season and grill the chicken for 6 minutes per side, then rest and slice.",
      "Mash the anchovies and garlic to a paste, then whisk with the yolk, mustard and lemon.",
      "Whisk in the oil slowly until the dressing emulsifies and thickens.",
      "Toss the romaine in the dressing, then add the chicken, croutons and parmesan.",
    ],
  },
  {
    slot: "Lunch",
    title: "Reuben Sandwich",
    description: "Grilled rye with pastrami, sauerkraut, Swiss and Russian dressing.",
    cuisine: "American",
    dietary_tags: [],
    time_minutes: 20,
    servings: 2,
    ingredients: [
      "4 slices rye bread",
      "300g pastrami",
      "150g sauerkraut, squeezed dry",
      "4 slices Swiss cheese",
      "4 tbsp Russian dressing",
      "30g butter, softened",
    ],
    steps: [
      "Squeeze the sauerkraut as dry as you can or the sandwich will steam rather than crisp.",
      "Warm the pastrami briefly in a pan or steamer.",
      "Build with dressing, cheese, pastrami, sauerkraut and more cheese so the cheese seals both sides.",
      "Butter the outsides and grill over medium-low heat for 4 minutes per side until deeply golden.",
    ],
  },
  {
    slot: "Dinner",
    title: "Roast Chicken with Root Vegetables",
    description: "Whole herb-rubbed chicken roasted over carrots and potatoes.",
    cuisine: "American",
    dietary_tags: ["Gluten-Free"],
    time_minutes: 90,
    servings: 4,
    ingredients: [
      "1 whole chicken (about 1.6kg)",
      "4 carrots, in chunks",
      "600g potatoes, quartered",
      "2 onions, quartered",
      "3 tbsp olive oil",
      "1 tbsp fresh thyme leaves",
      "1 lemon, halved",
      "30g butter, softened",
    ],
    steps: [
      "Salt the chicken all over and leave uncovered in the fridge for an hour if you can — it dries the skin so it crisps.",
      "Toss the vegetables with the oil in a roasting tin.",
      "Rub the chicken with butter and thyme, put the lemon in the cavity, and set it on the vegetables.",
      "Roast at 200°C for 70-80 minutes until the juices from the thigh run clear.",
      "Rest for 15 minutes before carving.",
    ],
  },
  {
    slot: "Dinner",
    title: "Pan-Seared Salmon with Lemon Butter",
    description: "Crisp-skinned salmon in a lemon and caper butter sauce.",
    cuisine: "American",
    dietary_tags: ["Gluten-Free", "Pescatarian"],
    time_minutes: 25,
    servings: 2,
    ingredients: [
      "2 salmon fillets, skin on",
      "2 tbsp olive oil",
      "40g butter",
      "1 lemon, juiced",
      "1 tbsp capers",
      "2 cloves garlic, minced",
      "Fresh dill, chopped",
    ],
    steps: [
      "Pat the skin completely dry and season; moisture is what stops skin crisping.",
      "Lay the fillets skin-side down in hot oil and press flat for 20 seconds, then cook 5 minutes without moving them.",
      "Flip and cook 2 minutes more, then remove.",
      "Melt the butter in the pan with the garlic and capers, add the lemon, and spoon over the fish with dill.",
    ],
  },
  {
    slot: "Dinner",
    title: "BBQ Pulled Pork",
    description: "Shoulder cooked low until it shreds, tossed in a tangy sauce.",
    cuisine: "American",
    dietary_tags: ["Dairy-Free"],
    time_minutes: 300,
    servings: 6,
    ingredients: [
      "2kg pork shoulder, bone in",
      "3 tbsp brown sugar",
      "2 tbsp smoked paprika",
      "1 tbsp garlic powder",
      "1 tbsp mustard powder",
      "2 tsp salt",
      "250ml cider vinegar",
      "200ml barbecue sauce",
      "6 soft rolls",
    ],
    steps: [
      "Rub the pork all over with the sugar, spices and salt and leave overnight if possible.",
      "Roast at 140°C for about 5 hours, basting with the vinegar every hour, until a fork twists freely in the meat.",
      "Rest 30 minutes, then pull the meat apart with two forks, discarding large lumps of fat.",
      "Toss with the pan juices and barbecue sauce and pile into rolls.",
    ],
  },

  // ---------------------------------------------------------------- British
  {
    slot: "Breakfast",
    title: "Full English Breakfast",
    description:
      "Bacon, sausage, eggs, beans, mushrooms and tomato on one plate.",
    cuisine: "British",
    dietary_tags: [],
    time_minutes: 35,
    servings: 2,
    ingredients: [
      "4 pork sausages",
      "4 rashers back bacon",
      "2 eggs",
      "1 can (400g) baked beans",
      "150g mushrooms, halved",
      "2 tomatoes, halved",
      "2 slices bread",
      "1 tbsp oil",
    ],
    steps: [
      "Start the sausages first over low heat; they need 15-20 minutes and burn if rushed.",
      "Add the bacon after 10 minutes, then the mushrooms and tomatoes to the same pan.",
      "Warm the beans and toast the bread.",
      "Fry the eggs last so they arrive hot, and plate everything together.",
    ],
  },
  {
    slot: "Breakfast",
    title: "Porridge with Golden Syrup",
    description: "Oats cooked slowly with milk until thick and glossy.",
    cuisine: "British",
    dietary_tags: ["Vegetarian"],
    time_minutes: 15,
    servings: 2,
    ingredients: [
      "100g rolled oats",
      "400ml whole milk",
      "200ml water",
      "1 pinch salt",
      "2 tbsp golden syrup",
      "1 handful berries",
    ],
    steps: [
      "Bring the oats, milk, water and salt to a gentle simmer.",
      "Cook for 8-10 minutes, stirring often, until thick and creamy.",
      "Rest off the heat for a minute to thicken further.",
      "Serve with golden syrup poured over and berries alongside.",
    ],
  },
  {
    slot: "Lunch",
    title: "Jacket Potato with Cheese and Beans",
    description: "Crisp-skinned baked potato split and loaded with beans and cheddar.",
    cuisine: "British",
    dietary_tags: ["Vegetarian", "Gluten-Free"],
    time_minutes: 80,
    servings: 2,
    ingredients: [
      "2 large baking potatoes",
      "1 tbsp olive oil",
      "1 tsp flaky salt",
      "1 can (400g) baked beans",
      "100g mature cheddar, grated",
      "20g butter",
    ],
    steps: [
      "Prick the potatoes all over, rub with oil and salt, and set them directly on the oven shelf.",
      "Bake at 200°C for 70-80 minutes until the skin is crisp and the flesh gives completely.",
      "Split open, fork through the butter, and season.",
      "Pile on the hot beans and cheddar so the cheese melts into the potato.",
    ],
  },
  {
    slot: "Lunch",
    title: "Ploughman's Lunch",
    description:
      "Cold plate of cheese, ham, pickle, bread and apple — assembled, not cooked.",
    cuisine: "British",
    dietary_tags: [],
    time_minutes: 10,
    servings: 2,
    ingredients: [
      "200g mature cheddar",
      "150g thick-cut ham",
      "3 tbsp Branston pickle",
      "2 crusty bread rolls",
      "1 apple, sliced",
      "4 pickled onions",
      "30g butter",
      "1 handful salad leaves",
    ],
    steps: [
      "Take the cheese out of the fridge 30 minutes ahead so its flavour opens up.",
      "Cut the cheese into thick wedges and arrange with the ham on a board.",
      "Add the pickle, pickled onions, apple and salad leaves in separate piles.",
      "Serve with buttered bread.",
    ],
  },
  {
    slot: "Dinner",
    title: "Shepherd's Pie",
    description:
      "Minced lamb in gravy under a browned mashed potato crust.",
    cuisine: "British",
    dietary_tags: [],
    time_minutes: 75,
    servings: 4,
    ingredients: [
      "600g minced lamb",
      "1 onion, diced",
      "2 carrots, diced",
      "2 tbsp tomato paste",
      "1 tbsp Worcestershire sauce",
      "400ml lamb or beef stock",
      "1 tbsp plain flour",
      "1kg potatoes, peeled",
      "80g butter",
      "100ml milk",
    ],
    steps: [
      "Brown the lamb well, then add the onion and carrot and cook 8 minutes.",
      "Stir in the flour and tomato paste, then the stock and Worcestershire sauce, and simmer 25 minutes until thick.",
      "Boil the potatoes until tender, drain thoroughly, then mash with the butter and milk.",
      "Spread the mash over the lamb and rough the surface with a fork so it crisps.",
      "Bake at 200°C for 25 minutes until browned at the peaks.",
    ],
  },
  {
    slot: "Dinner",
    title: "Fish and Chips",
    description: "Beer-battered white fish with thick-cut chips.",
    cuisine: "British",
    dietary_tags: [],
    time_minutes: 50,
    servings: 2,
    ingredients: [
      "2 large cod or haddock fillets",
      "800g floury potatoes, cut into thick chips",
      "150g plain flour",
      "200ml cold beer",
      "1 tsp baking powder",
      "Oil, for deep frying",
      "1 lemon, in wedges",
      "Mushy peas, to serve",
    ],
    steps: [
      "Fry the chips at 130°C for 6 minutes to cook them through, then drain and cool — this first fry is what makes them fluffy inside.",
      "Whisk the flour, baking powder and cold beer into a batter; keep it cold.",
      "Raise the oil to 180°C, dip the fish and fry 6-7 minutes until deep gold.",
      "Fry the chips a second time at 180°C for 3 minutes until crisp.",
      "Salt everything at once and serve with lemon and mushy peas.",
    ],
  },
  {
    slot: "Dinner",
    title: "Bangers and Mash",
    description: "Sausages with buttery mash and a deep onion gravy.",
    cuisine: "British",
    dietary_tags: [],
    time_minutes: 45,
    servings: 4,
    ingredients: [
      "8 pork sausages",
      "1kg floury potatoes, peeled",
      "100g butter",
      "120ml warm milk",
      "3 onions, thinly sliced",
      "1 tbsp plain flour",
      "500ml beef stock",
      "1 tsp Worcestershire sauce",
    ],
    steps: [
      "Cook the sausages slowly in a pan over medium-low heat for 20 minutes, turning, until evenly browned.",
      "Cook the onions in butter over low heat for 20 minutes until soft and sweet, then stir in the flour.",
      "Add the stock and Worcestershire sauce and simmer 10 minutes until the gravy coats a spoon.",
      "Boil and mash the potatoes with the butter and warm milk until smooth, and season well.",
      "Serve the sausages on the mash with the onion gravy poured over.",
    ],
  },
];
