-- ============================================================
-- Māka — Student login upgrade
-- Run this ONCE in your Supabase dashboard:
--   supabase.com → your project → SQL Editor → New query →
--   paste this whole file → Run
-- (Safe to run after supabase-student-hub.sql, which you've
--  already run. Safe to re-run.)
-- ============================================================

-- ── 1. Link results to students properly ─────────────────────
-- New results save the real students.id, so two students who
-- share a first name never get each other's work.
alter table public.student_results
  add column if not exists student_id uuid references public.students(id) on delete set null;

create index if not exists idx_student_results_student_id
  on public.student_results(student_id);

-- Long-lived signed URL to the stored PDF, generated by the
-- teacher's session at save time, so the student hub can show
-- "View your work" without opening the storage bucket to anon.
alter table public.student_results
  add column if not exists pdf_url text;

-- Backfill student_id for existing rows — only where exactly ONE
-- student's first name matches the file name (no ambiguity).
update public.student_results r
set student_id = m.sid
from (
  select r2.id as rid, min(s.id::text)::uuid as sid
  from public.student_results r2
  join public.students s
    on s.teacher_id = r2.teacher_id
   and r2.file_name ilike '%' || split_part(s.name,' ',1) || '%'
  where r2.student_id is null
  group by r2.id
  having count(*) = 1
) m
where r.id = m.rid;

-- ── 2. Friendly login codes (e.g. KEA-4912) ──────────────────
alter table public.students
  add column if not exists login_code text unique;

create or replace function public.gen_login_code()
returns text
language plpgsql
volatile
as $$
declare
  birds text[] := array['KEA','TUI','MOA','RURU','KIWI','WEKA','KAKA','HUIA','KAHU','TARA','TOROA','KOTARE','KERERU','TAKAHE','PUKEKO','KAKAPO'];
  c text;
begin
  loop
    c := birds[1 + floor(random() * array_length(birds,1))::int]
         || '-' || lpad(floor(random() * 10000)::int::text, 4, '0');
    exit when not exists (select 1 from public.students where login_code = c);
  end loop;
  return c;
end $$;

-- Backfill codes for existing students
update public.students
  set login_code = public.gen_login_code()
  where login_code is null;

-- Auto-assign codes to students added from now on
create or replace function public.set_student_codes()
returns trigger
language plpgsql
as $$
begin
  if new.login_code is null then
    new.login_code := public.gen_login_code();
  end if;
  if new.share_code is null then
    new.share_code := replace(replace(encode(gen_random_bytes(12),'base64'),'/','x'),'+','y');
  end if;
  return new;
end $$;

drop trigger if exists trg_students_codes on public.students;
create trigger trg_students_codes
  before insert on public.students
  for each row execute function public.set_student_codes();

-- ── 3. Upgraded student_hub RPC ───────────────────────────────
-- Accepts EITHER the old long share_code (old links keep working)
-- OR the friendly login code (case-insensitive, spaces trimmed).
-- Results are matched by student_id first; the old first-name
-- match only applies to legacy rows that have no student_id.
create or replace function public.student_hub(code text)
returns json
language sql
security definer
set search_path = public
as $$
  with stu as (
    select * from students
    where share_code = code
       or upper(login_code) = upper(trim(code))
    limit 1
  )
  select json_build_object(
    'student', (
      select json_build_object('name', name, 'year_level', year_level)
      from stu
    ),
    'results', (
      select coalesce(json_agg(json_build_object(
        'id', r.id,
        'created_at', r.created_at,
        'criteria_total', r.criteria_total,
        'overall_score', r.overall_score,
        'criteria', r.criteria,
        'strengths', r.strengths,
        'next_steps', r.next_steps,
        'pdf_url', r.pdf_url,
        'session_name', se.name,
        'learning_area', se.learning_area,
        'session_date', se.created_at
      ) order by r.created_at), '[]'::json)
      from stu s
      join student_results r
        on r.teacher_id = s.teacher_id
       and (r.student_id = s.id
            or (r.student_id is null
                and r.file_name ilike '%' || split_part(s.name,' ',1) || '%'))
      left join sessions se on se.id = r.session_id
    )
  );
$$;

grant execute on function public.student_hub(text) to anon;
